### ISSUE TITLE
.Net Client 1.x Metric type Capitalization

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus-net/prometheus-net#103]
We have a large number of applications using the 1.3.5 exporter currently and we would like to be able to fix a compatibility issue with the new Prometheus that prevents scrapes because metric name is capitalized.

Is there a specific commit that this Nuget package was built from that we could fork to fix this issue ourselves and allow our teams more time to migrate?

**Comment by sandersaares** [comment]
The fix for the capitalization defect was in https://github.com/prometheus-net/prometheus-net/commit/e60c00e0650abc690da4dcefec78fde895ac21e2

**Comment by sandersaares** [comment]
I am afraid I do not have exact information on this. However, https://github.com/prometheus-net/prometheus-net/commit/77428872f1ae94f81f72badf67eaa58654bce6a9 seems to be the last commit before the 2.0 changes started, so that is probably your best bet.

**Comment by sandersaares** [comment]
I took a closer look at the timestamps and it looks like actually https://github.com/prometheus-net/prometheus-net/commit/d9c41146f913978dabaa1651d71d4a701dbbaf92 is the last commit before the NuGet package was published.

The original maintainer who published that release is no longer active and I do not know of any way to narrow it down more, so I close the issue as you suggested.
