### ISSUE TITLE
Assemblies are not strong-named

### ISSUE THREAD

**Issue by ferrata** [prometheus-net/prometheus-net#104]
### The problem

Assemblies are not [strong-named](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies). Some projects (most of the projects that I am working on as a professional developer) require strong-naming. Any library that is referenced from such project is required to have a strong-name. Not having a strong-name in `prometheus-net` will force users to create their own "unofficial" forks and prevent them from using this repository as a *single library release source*. 

### Proposed resolution

Update project assemblies by adding strong-names.

### Implications

This is going to be a breaking change for all existing users of the library.

Although a non-strong-named project can still reference strong-named library, switching from non-strong-named library to a strong-named one will require the user's project to be updated. Project references to the library will have to be changed to reflect the correct version of the `prometheus-net` library. Particularly `assemblyIdentity` tags will have to contain correct `publicKeyToken` values.

**Comment by sandersaares** [comment]
Okay, this sounds like a reasonable enhancement. Will be included in vNext.

**Comment by sandersaares** [comment]
Version 3.0.0 is now published, with this change included.
