### ISSUE TITLE
Implement OpenMetrics export format

### ISSUE THREAD

**Issue by sandersaares** [prometheus-net/prometheus-net#106]
There seems to be some standardization ongoing for the export format. Let's include it in prometheus-net.

Text format is mandatory. Protobuf is optional. Let's start with text.

On hold for now because I can't even find a draft of it anywhere.

**Comment by vsliouniaev** [comment]
[Draft is available here, but it is only a draft](https://docs.google.com/document/d/1KwV0mAXwwbvvifBvDKH_LU1YjyXE_wxCkHNoCGq1GX0/edit)

via:
https://github.com/prometheus/prometheus/releases/tag/v2.5.0 -> 
https://github.com/prometheus/prometheus/pull/4700

**Comment by sandersaares** [comment]
https://github.com/OpenObservability/OpenMetrics/blob/master/markdown/metric_exposition_format.md something also here. This OpenMetrics doesn't seem to be moving anywhere fast, though.

**Comment by sandersaares** [comment]
I am going to close this for now, since OpenMetrics does not seem to be an actively developed format and is therefore unlikely to be meaningful for this library in the near future. Maybe if they resurrect the task force and actually publish something one day, this deserves a revisit.

**Comment by joe-elliott** [comment]
@sandersaares 

The [OpenMetrics standard](https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md) has been published and support has been added (or is being added) to the Ruby/Go/Java clients.

Can we reopen and readdress this?
