### ISSUE TITLE
Default metrics with 'windows' suffix

### ISSUE THREAD

**Issue by tdabasinskas** [prometheus-net/prometheus-net#114]
By default, the library [adds the following metrics](
https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus.NetStandard/Advanced/DotNetStatsCollector.cs#L48-L53):

```csharp
_virtualMemorySize = metrics.CreateGauge("process_windows_virtual_bytes", "Process virtual memory size");
_workingSet = metrics.CreateGauge("process_windows_working_set", "Process working set");
_privateMemorySize = metrics.CreateGauge("process_windows_private_bytes", "Process private memory size");
_openHandles = metrics.CreateGauge("process_windows_open_handles", "Number of open handles");
_numThreads = metrics.CreateGauge("process_windows_num_threads", "Total number of threads");
_pid = metrics.CreateGauge("process_windows_processid", "Process ID");
```

Since .NET Core applications can run and Linux as well, naming of these metrics is really confusing. Is there any reason we have `*_windows_*` inside the name and, if not, can it be removed (so, `process_windows_virtual_bytes` would become `process_virtual_bytes`).

That would be a breaking change, so, if done, it would require a new major release, though.

**Comment by sandersaares** [comment]
Seems sensible. There were some API changes anyway, so a new major version is coming soon. I will process this issue when going over the builtin metrics before next release.

**Comment by sandersaares** [comment]
Version 3.0.0 is now published, with this included.
