### ISSUE TITLE
Outdated docs?

### ISSUE THREAD

**Issue by facundofarias** [prometheus-net/prometheus-net#115]
Hello,

I am trying to implement a timer, and when I try the sample stated in the docs:
```
var summary = Metrics.CreateSummary("mySummary", "help text");
using (summary.NewTimer())
{
    Console.WriteLine("This action is timed");
}
```
The method **NewTimer** does not exist in the object Summary. 
Any ideas?

Thanks.

**Comment by sandersaares** [comment]
The documentation in the master branch has been updated for the upcoming 3.0 release. However, this release is not yet available.

In version 2.x, the Timer is available as `Gauge.Timer` and has a more limited set of functionality.

I expect 3.0 will be published late January. However, I will publish a preview version of it right now, so if you wish to experiment with some 3.0 features you can do so.
