### ISSUE TITLE
Metrics not showing up for mono but working on windows

### ISSUE THREAD

**Issue by dhams232** [prometheus-net/prometheus-net#117]
I want collect metrics information on Mono system. I have following environment using docker
.NET Framework 4.6.1
Mono JIT compiler version 5.4.1.6
Architecture: amd64

I have use following code get metrics to publish.
var metricServer = new MetricServer(port: 1234);
metricServer.Start();

On windows machine I am successfully getting metrics information. 
How I should get metrics on the mono system?
Any suggestion ?

**Comment by dhams232** [comment]
Anyone try prometheus-net on mono system? Please help

**Comment by sandersaares** [comment]
Can you clarify the nature of the problem? What happens if you try this on Mono? Is the port not opened? Do you get an exception? Do connections fails?

A minimal repro project would be great to have, if you can supply one.

**Comment by JosephWoodward** [comment]
Having seen this issue I've just given it a try and everything appears to be working as expected.

I'm using:

```
.NET Framework 4.6.1
Mono JIT compiler version 5.18.0.225
Architecture:  amd64
```

**Comment by sandersaares** [comment]
Thanks for the verification @JosephWoodward .

I will close this issue for now due to lack of information. Everything seems to work. If you continue to experience issues @dhams232 please feel free to commend with additional details.

**Comment by dhams232** [comment]
Sorry for delaying in reply.

We are using following environment:

Mono JIT compiler version 5.4.1.6 (tarball Wed Nov 8 20:37:24 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
  TLS: __thread
  SIGSEGV: altstack
  Notifications: epoll
  Architecture: amd64
  Disabled: none
  Misc: softdebug 
  LLVM: supported, not enabled.
  GC: sgen (concurrent by default)

We are running WebRTC server on mono behind load balancer. We have two endpoints e.g. /mywebsync.ashx to check server is up or not and /myhealthcheck.ashx to check server health.

on mono machine we are not able to retrieve metrics information. We are trying using default default configuration e.g. the /metrics URL as mentioned  on github.

Windows system same code is working and we are able to retrieve metrics information.

Anyone has tried this library as mentioned environment?

Please let us know about your suggestions.

**Comment by dhams232** [comment]
Open as new issue https://github.com/prometheus-net/prometheus-net/issues/131#issue-410822787
