### ISSUE TITLE
Best way to create multiple metrics with labels

### ISSUE THREAD

**Issue by JJoe2** [prometheus-net/prometheus-net#119]
What is the difference between the following two methods of creating labelled metrics (Counter in this example), and under what circumstances is each recommended?

1. Create a single Counter instance and then create multiple children with the relevant label values:

    var config = new CounterConfiguration { LabelNames = new[] { "MyLabel" };
    var counter = Metrics.CreateCounter("MyName", "MyHelp", config);
    
    ICounter counter1 = counter.WithLabels( new[] { "MyLabelValue1" });
    ICounter counter2 = counter.WithLabels( new[] { "MyLabelValue2" });

2. Create a new Counter instance for each label value:

    var config = new CounterConfiguration { LabelNames = new[] { "MyLabel" };
    ICounter counter1 = Metrics.CreateCounter("MyName", "MyHelp", config)
              .WithLabels(new[] { "MyLabelValue1" });

    ...

    ICounter counter2 = Metrics.CreateCounter("MyName", "MyHelp", config)
              .WithLabels(new[] { "MyLabelValue2" });

Approach 2 has the advantage that I can create counters that use the same label names independently in independent classes.  But it's not clear to me if there is a downside in creating the same Counter more than once.

**Comment by sandersaares** [comment]
The two are equivalent. The second CreateCounter call will just return the same instance as the first one.
