### ISSUE TITLE
Create metrics using attributes

### ISSUE THREAD

**Issue by omerlh** [prometheus-net/prometheus-net#120]
Currently, creating a metrics requires manual wiring of properties, for example:
```csharp
var reposGauge = Metrics.CreateGauge("github_repos", "Github Repositories.", 
            new GaugeConfiguration
            {
                LabelNames = new string[] {"name", "organization"}
            });
```
It will be nice to use attributes for cleaner syntax:
```csharp
[Gauge("github_repos", Description="GitHub Repositories", LabelsNames = new string[] {"name", "organization"} /* not sure if a valid syntax */]
Gauge ReposGauge
{
  get;
}
```

**Comment by sandersaares** [comment]
Thank you for the feature suggestion. The initialization complexity this would add does not seem to outweigh any potential benefits from using a different syntax, so this feature will not be put on the backlog. However, if you find this style of initialization beneficial then I imagine it would be possible for you to create a custom library that exists as a layer on top of prometheus-net and initializes the metrics in a style more convenient to you.
