### ISSUE TITLE
Does anyone have a pre-built Grafana dashboard?

### ISSUE THREAD

**Issue by JosephWoodward** [prometheus-net/prometheus-net#122]
Hi, love this NuGet package. I'm wondering, does anyone have a pre-built Grafana dashboard around the metrics exposed by default when using this package? If so, I'd be really interested in seeing it, and I wonder whether it would be worth adding it to this repository as a means of lowering the barrier of entry for those interested in using it but are still new to Prometheus and PromQL.

**Comment by sandersaares** [comment]
I know Grafana has some "App Store" style thing for dashboards. Maybe a "showcase" there? However, this is more "Prometheus" in general than "prometheus-net", so I imagine it would be better as a separate undertaking, not specifically related to this library.

This might be along the lines of "How to visualize Prometheus metrics of different types". The specific metrics would be quite usecase-specific, so it should be something generic that could be applied as an example for different cases. Not meant to be used as-is, in other words.

I should probably close this issue but I leave it here in case someone wants to contribute something on this angle and/or for discussion. We can open up another project in this org if someone feels like maintaining some relevant Grafana templates.

**Comment by onepos-zaika** [comment]
Hello! A demo Grafana dashboard does help new comers like me a lot. Because we are going to build one Grafana template, is it a good idea to post it somewhere which can be shared by everyone who needs it?

**Comment by AChehre** [comment]
I have created a simple dashboard: [prometheus-net - 10427](https://grafana.com/dashboards/10427)
@sandersaares I'm ok with creating a project in this org and I hope others join to maintain

**Comment by onepos-zaika** [comment]
Hello AChehre,
Thank you. I have just added to my grafana. It works great except the start time of process has multiple series error.

**Comment by AChehre** [comment]
@onepos-zaika Thanks for the feedback, I changed query with `time() - process_start_time_seconds`  as  [Grafana demo](https://play.grafana.org/d/000000029/prometheus-demo-dashboard?tab=queries&orgId=1&refresh=5m&fullscreen&edit&panelId=10) for showing the uptime.

> Note that this does not actually return the current time, but the time at which the expression is to be evaluated [time()](https://prometheus.io/docs/prometheus/latest/querying/functions/#time)

I think we have a problem with displaying start time on Grafana. 
Grafana cant convert our process_start_time_seconds to DateTime format ("YYYY-MM-DD HH:mm:ss"), Grafana shows Time and doesn't show the Date, But as I see in [epochconverter ](https://www.epochconverter.com/) our timestamp is looking good.

**Comment by NazmiAltun** [comment]
Having a standard grafana dashboard  would be great  ,especially for HTTP metrics.  A dashboard that has one panel for displaying  throughput  of the app (also throughput per endpoint) and one panel for displaying HTTP error interval, would be great.

**Comment by sandersaares** [comment]
I have created https://github.com/prometheus-net/grafana-dashboards and added you as collaborator @AChehre. Feel free to migrate your dashboard template source code there for better visibility (if you want).

I am currently working on a dashboard template for ASP.NET Core metrics, which I plan to publish shortly.

**Comment by sandersaares** [comment]
Here's my first attempt at an ASP.NET Core metrics dashboard: https://grafana.com/grafana/dashboards/10915

**Comment by JosephWoodward** [comment]
Oh nice, looks good. I like the heatmap!

**Comment by AChehre** [comment]
> I have created https://github.com/prometheus-net/grafana-dashboards and added you as collaborator @AChehre. Feel free to migrate your dashboard template source code there for better visibility (if you want).
> 

Ok, Sure, tnx

**Comment by sandersaares** [comment]
I will close this issue since we now have a couple example dashboards. More contributions are, of course welcome!

**Comment by JosephWoodward** [comment]
Sounds good, great work 👍

**Comment by ElectroBuddha** [comment]
Hi, any chance of sharing grafana dashboard from the current Readme ?

![](https://github.com/prometheus-net/prometheus-net/blob/master/Screenshot.png)

**Comment by vhatuncev** [comment]
> Hi, any chance of sharing grafana dashboard from the current Readme ?
> 
> [Screenshot](https://github.com/prometheus-net/prometheus-net/blob/master/Screenshot.png)

Vote for this, any chance to get this dashboard? @sandersaares
