### ISSUE TITLE
Add BasicAuth

### ISSUE THREAD

**Issue by Marcel-B** [prometheus-net/prometheus-net#125]
It would be nice to have a way, to set BasicAuth for accessing secured push gateways.

**Comment by mrich316** [comment]
What would you think of exposing IHttpClientFactory in MetricsPusher constructor to allow any type of customization of the HttpClient, like custom security headers or retries? 

That would come at a cost: extra dependency on Microsoft.Extensions.Http but also solve DNS changes of the pushgateway that a static HttpClient cannot resolve by itself.

But we could mitigate the extra dependency by creating a factory of our own, and implementers could add Microsoft.Extensions.Http only for advanced scenarios.

Reference: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

What do you think?

**Comment by sandersaares** [comment]
Good idea. I will implement it in a similar way, although with a simpler API to avoid adding more interafces to the library (or introducing name conflicts).
