### ISSUE TITLE
UseHttpMetrics and MetricsServer result in 0 seconds sum for request duration?

### ISSUE THREAD

**Issue by daniel-harrison-cko** [prometheus-net/prometheus-net#126]
Here is my `Startup.cs`:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMetricServer();
            app.UseHttpMetrics();

            app.UseMvc();
}
```

The metrics server always reports that `http_request_duration_seconds_sum` is `0` even after requests have come in and occasionally take several seconds?

Doesn't seem right to me. Thoughts?

**Comment by sandersaares** [comment]
Thank you for the report! Looks like there has indeed been a regression that was not covered by tests. I have added a test to try catch such errors in the future and will publish a fix right away.

**Comment by daniel-harrison-cko** [comment]
Thank you for the quick fix.
