### ISSUE TITLE
ICollector replacment

### ISSUE THREAD

**Issue by shvez** [prometheus-net/prometheus-net#129]
Hi, there.

I found out that in the new version you do not support ICollector interface anymore.  I should admit that we heavily used it. With its help, we have converted Windows performance counters data into Prometheus metrics.
Yes, I see that without the creation of all these temporary MetricFamily/Counters objects it will work more efficient, but I'm not sure how to plugin in my self into your flow.
I saw your next recommendation: `Just generate a Prometheus exporter output document yourself if you need to export arbitrary data.` But I'm not sure how to do this using the new version of your lib. One of our goals is to have only **one port scraped** by Prometheus.  So, I'm thinking about using Collector class for this. so, then when 'CollectAndSerialize' method is called, I will just serialize data I have and that is basically it.

Is this how you planned it to be? is there any issues with my idea?

best,
Ilya

**Comment by shvez** [comment]
Because that feature was a key feature for us, I'm asking whether it is possible to add ICollector interface with will have only Name property and CollectAndSerialize method, so that it will be easy to plug our stuff into your lib?

**Comment by sandersaares** [comment]
When reviewing the library API surface, the ability to export arbitrary data was removed in 3.0 because it seemed to just be something that "goes through" the library without the library really playing much part in providing additional value. This was code that complicated library design without that big of a value-add.

The Prometheus export format is very simple, as you know:

```
# HELP name help
# TYPE name type
name{labelkey1="labelvalue1",labelkey2="labelvalue2"} 123.456
```

Maintaining a public API surface just to allow some external data to be converted to a different shape of data seems not to be worth it from a cost/benefit angle of the maintenance, especially considering the trivial nature of the data format (it is very easy to generate such output documents).

I would like to better understand your scenario to see if there is anything I can do to help you along the path here. Does the set of performance counters change often in your setup? That is, would it be inconvenient to represent them as just Gauge objects? I assume some dynamic nature of the data is the reason behind your implementation.

**Comment by shvez** [comment]
@sandersaares, we have a native library which we can not change (as usual ;)) and it provides 500+ different windows performance counters using the first version of windows perf monitor API. That means that I get a memory segment which I should parse to get descriptions and values of counters and categories. 
Yes, that is true, that I could create gauges to handle this, but, first, I'm sure that this just wasting of resources. Second, I may send some data not as Gauge but as Counter. This probably will help to keep that data in a more optimized manner. I'm not sure here. Fix me If I'm wrong.

So, yes, you are right, that I may create a separate document and somehow open listener and handle a request from Prometheus. But this will increase the complexity of my code, even if I will just copy ideas from your code. And It will also increase configuration complexity. Because we will need to configure more ports for scraping. 
The real value of version 2.1.3 for me(us) is that the library allows me to create one common Prometheus document using different sources, different approaches. Yes, we also create gauges and counters in our managed code.

yes, that is true that your API was more complex than it is now. But this does not mean that cannot solve my problem. To be honest as far as I may see change is trivial. The only thing I need just callback with reference to the serializer. Then I will be able to serialize my data and that is basically it. I will be able to serialize my data in an extremely performant way because I may cache names and descriptions and tags in binary form. All this was not possible with the previous version.
 I assume, that this can be achieved either by adding an extra callback type with IMetricsSerializer or by introducing ICollector interface. It seems to me that both of these ways are easy/cheap to support and they give enough flexibility to achieve all my goals using only your library.

best,
ilya

**Comment by shvez** [comment]
I would add even more. We are going to use timestamps at least for data which we got using perfmonitor API. You lib does not support this feature at all. So, if I would be able to serialize my data my self this also could help

best,
ilya

**Comment by phnx47** [comment]
@shvez If you can't use v3 in the future. You can try realize some functional in my fork: https://github.com/PrometheusClientNet/Prometheus.Client

I continue use ICollector. I support timestamp: https://github.com/PrometheusClientNet/Prometheus.Client/issues/18. And have one extra issue for timestap: https://github.com/PrometheusClientNet/Prometheus.Client/issues/21

**Comment by shvez** [comment]
@phnx47 thank you, I will think about it. But most probably I will do my for of this version. I like new library design more, then the old one

**Comment by sandersaares** [comment]
After a second pass of thinking on this, I still feel the same way - to support a functionaltiy for simply converting some other data to Prometheus data is out of scope of this library's intended feature set. This library is meant for reporting live data from ongoing processes in .NET code, not for general purpose Prometheus document generation.

Certainly, I can envision ways of doing it that would integrate well with the library. However, I need to constrain the scope to the most commonly needed feature set to ensure that I can pay sufficient attention to actually maintain it (as you see it even took me a month to return to this query - I am slow!).

My suggestion is to report your converted data set on a separate URL (merging the data set on the Prometheus database should be easy). This gives you complete freedom for the conversion but maintains your ability to use the library for .NET metrics reporting.

**Comment by shvez** [comment]
Just went back from vacation.

>My suggestion is to report your converted data set on a separate URL (merging the data set on the Prometheus database should be easy). This gives you complete freedom for the conversion but maintains your ability to use the library for .NET metrics reporting

if I would write everything my self, I would have complete freedom in any aspect of the program. But also I would have a lot of chances to create bugs. That is why I do not like your suggestion and would prefer to use ready to use code instead.  

Sad that we could not come to consensus. I see that you are trying to help me with my task by providing  CollectAndExportAsText. Thank you. But still this approach leaves for me some task which I do not want to have.
