### ISSUE TITLE
Excessive object creation

### ISSUE THREAD

**Issue by kimbell** [prometheus-net/prometheus-net#134]
In the MetricsFactory, this pattern is used: 

```cs
public Counter CreateCounter(string name, string help, CounterConfiguration configuration = null)
{
    configuration = configuration ?? CounterConfiguration.Default;

    var metric = new Counter(name, help, configuration.LabelNames, configuration.SuppressInitialValue);
    return (Counter)_registry.GetOrAdd(metric);
}
```

In the CollectorRegistry, we find

```cs
internal Collector GetOrAdd(Collector collector)
{
    var collectorToUse = _collectors.GetOrAdd(collector.Name, collector);

    if (!collector.LabelNames.SequenceEqual(collectorToUse.LabelNames))
        throw new InvalidOperationException("Collector with same name must have same label names");

    return collectorToUse;
}
```
The collector object is created in order to check if there is already registered one with that name. Except for the very first time, the object that was just created will not be used. Since these may be created as a result of new requests, the number of unneeded objects being created can become quite large. This will in turn impact garbage collection.

**Comment by kimbell** [comment]
#135 is a proposal to solve this.

**Comment by sandersaares** [comment]
I agree this allocation is excessive. I will fix it with a slightly different solution than your PR, to keep the code out of CollectorRegistry a bit more.
