### ISSUE TITLE
No means to fetch all labeled values in v3

### ISSUE THREAD

**Issue by djluck** [prometheus-net/prometheus-net#136]
In version 2 of prometheus-net, I could collect all unlabeled and labeled values of a metric by calling `ICollector.Collect()`. In v3, this introspective ability has been lost- the closest I can see is `Collector<TChild> .GetAllLabels` but this is marked `internal` (as is `Label`). Is it possible to make these methods and types publicly callable? I'm facing difficulty in upgrading https://github.com/djluck/prometheus-net.DotNetRuntime to use v3 for this reason.

**Comment by djluck** [comment]
I see also that properties like `Counter.Value` are gone too- it would be great to have access to these values as well.

**Comment by rwkarg** [comment]
This is also blocking us from upgrading to the v3 version of the prometheus-net package.

**Comment by djluck** [comment]
Hey @sandersaares, can I pester you for a response?

**Comment by sandersaares** [comment]
The collectors are intentionally designed to be written to by app code and to be read from only by serialization code. App code should treat metrics as write-only. The fact that serialization methods were exposed in v2 was an API design oversight and `Collect()` was never intended to be called by user code.

That being said, I would like to help you find a solution to you need. Can you outline exactly how/why you used the removed functionality? I might be able to suggest/provide an alternative approach.

As a general guideline, if you want some metrics to depend on previous values of the metric, you should keep track of the previous value yourself.

**Comment by djluck** [comment]
Hey @sandersaares, thanks for getting back to me.

So, there are two scenarios I am interested in obtaining `Gauge` / `Counter`/ `Histogram` values for:
1. **Creating composite metrics**. For example, I have two `Counters`- one tracking total process CPU use and the other tracking sub-process CPU use. When a Prometheus scrape occurs, I can calculate a new `Gauge` representing the percentage of CPU used by the sub-process. As you suggested, I can do this however without having access to the counter values (I'd keep track of the values myself).
2. **Testing collected values**. As I'm writing a library that publishes metrics, I need to test my code and verify that it's publishing the correct values- I can't (easily) do this without an API that exposes the metric values. This is probably the main reason I'd urge you to include a value inspection API.

**Comment by rwkarg** [comment]
We are sending metrics to an in-house metrics collection back end (push based) in addition to exposing Prometheus format metrics. Before we can upgrade, we'd need to set up an LTS process to export metrics from the local Prometheus installations to our centralized backend.

**Comment by sandersaares** [comment]
The following data is exposed on the public API:

* ICounter.Value (already in v3.0)
* IGauge.Value (already in v3.0)
* IHistogram.Count (v3.1)
* IHistogram.Sum (v3.1)

Is this data set sufficient? Anything else that I might have missed?

**Comment by djluck** [comment]
That's a great help @sandersaares. Is it possible to also make all observed labels visible too?

**Comment by sandersaares** [comment]
Sure. I will add Collector.GetAllLabelValues() to expose that data set.

**Comment by djluck** [comment]
Thanks heaps @sandersaares!

**Comment by sandersaares** [comment]
Preview nuget is uploading as I write this. I will push a stable version next week if no surprise problems reported.
