### ISSUE TITLE
ICollector Not Available Question

### ISSUE THREAD

**Issue by lowrylp** [prometheus-net/prometheus-net#138]
With the ICollector being removed is there a way on the scrape to set the value of a gauge to zero?

Previously I used the collector to reset gauge values when the scrap occurred.
This allowed my gauges to represent absolute values over the scape period.

Thanks.

**Comment by sandersaares** [comment]
This is not a usage that conforms to Prometheus data management best practices and will not be supported by this library except by accident.

If you wish to measure changes between different data points, the PromQL method `irate()` might be useful (though only in limited scenarios). In general, your data generation and applied analysis queries should be independent of scraping.

That being said, if you really want to do this you could probably emulate such behavior by using `AddBeforeCollectCallback` and before every collection subtracting from the gauge whatever value was present during the previous collection.
