### ISSUE TITLE
Missing CollectAll() / ScrapeHandler.ProcessScrapeRequest equivalent

### ISSUE THREAD

**Issue by pavkam** [prometheus-net/prometheus-net#139]
We have been using the CollectAll() to manually process and expose the metrics through our own endpoint.

In 3.0 we are unable to do so. Would it be possible to expose 
```
                                using (var serializer = new TextSerializer(delegate
                                    {
                                        response.ContentType = PrometheusConstants.ExporterContentType;
                                        response.StatusCode = 200;
                                        return response.OutputStream;
                                    }, leaveOpen: false))
                                {
                                    _registry.CollectAndSerialize(serializer);
                                }
```
as a public helper method?

We are not going to ever use MetricServer and all related methods are internal at this point.

**Comment by jpoehls** [comment]
I'm in a similar situation. We used `CollectAll()` a couple of ways using the 2.3.x package but both scenarios are broken in 3.x with no clear migration path:

1. called `CollectAll()` periodically (on a timer) to dump metrics to a log file -- (don't ask :) )
2. called `CollectAll()` and serialized to JSON manually to push to our own version of a "pushgateway"
3. implemented a custom `ICollector` as a way to automatically add label names/values to all metrics our system collects before outputting them

**Comment by connor4312** [comment]
This functionality would be super useful. Not all of us use Kestrel/asp.net and, since serialization methods are marked as internal, that renders this library unfeasible to use.

**Comment by sandersaares** [comment]
Thank you for the examples of relevant use cases. I will attempt to provide a mechanism to export a Prometheus document without the use of a MetricServer. Hopefully that solves most of your needs.

For any custom data processing (e.g. serialization to JSON) you would need to parse the Prometheus document, which is an extra step compared to v2, since the intermediate object representation no longer exists.

**Comment by sandersaares** [comment]
I have added `CollectorRegistry.CollectAndExportAsText(Stream)` to support metric data export via arbitrary custom endpoints.

You can parse the text document and perform any custom manipulation you wish, for extra custom scenarios, before export.

I will publish this as preview version later today, after going through other open issues, and a stable version next week. If you have any more feedback for me on this point, please feel free to share.

**Comment by sandersaares** [comment]
Stable version uploading now. Method became async meanwhile. `CollectAndExportAsTextAsync()`

**Comment by connor4312** [comment]
Awesome thank you!
