### ISSUE TITLE
Kestrel on .NET Core 3.0 Preview3 throws InvalidOperationException

### ISSUE THREAD

**Issue by alexeyzimarev** [prometheus-net/prometheus-net#140]
Kestrel for the next version of .NET Core seems to have breaking changes.

Right now, in the latest preview it throws then I try to fetch metrics:

```
InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(byte[] buffer, int offset, int count)
System.IO.BufferedStream.Flush()
System.IO.BufferedStream.Dispose(bool disposing)
System.IO.Stream.Close()
Prometheus.TextSerializer.Dispose()
Prometheus.MetricServerMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sandersaares** [comment]
Thanks for reporting! I am uploading a preview package `3.1.0-pre-006304-959164e` with a fix. If you have a moment, please try the preview package and report back if it solves the problem for you.

Stable package to be published later this week.

**Comment by alexeyzimarev** [comment]
Nice :) I have fixed it myself yesterday in my fork, so I actually planned to submit a PR :)
