### ISSUE TITLE
Import metrics

### ISSUE THREAD

**Issue by marufbd** [prometheus-net/prometheus-net#142]
Would be nice to have a corresponding import metrics function just like the :
`await Metrics.DefaultRegistry.CollectAndExportAsTextAsync(outputStream);`

The usecase is, my program is collecting different metrics from different endpoint and holding just the current state of all metrics, if it can store that immemory state to a file and restrive it on startup it can provide an up-to-date value all time.

**Comment by sandersaares** [comment]
prometheus-net is intended for instrumenting a running application with metrics specific to that app; workflows where data comes from external sources are possible by coincidence (modeling those metrics as app's own metrics) but this library is not really intended as a general purpose "xyz-to-prometheus" data transformer, so this is a bit outside the intended scope of usage.

If you wish to persist the state of metrics between app restarts, you will have to use some custom mechanism for that. I will close this feature request as rejected.
