### ISSUE TITLE
QUESTION: How can I have multiple scrape endpoints in ASP.NET Core

### ISSUE THREAD

**Issue by shahabganji** [prometheus-net/prometheus-net#143]
Hello, I am using `prometheus-net.AspNetCore:3.1.0` and I want to have multiple end points, one for health check of the application and another for my custom metrics, How can I achieve this goal? How can I tell the `Metrics` class to create `Counters`, for instance, for which end point?

One more question is that is there anyway to remove some metrics or reset them, when the collecting process ended? or have a `AddAfterCollectCallBack` like `Metrics.DefaultRegistry.AddBeforeCollectCallback`

Thanks in Advance,
Saeed

**Comment by sandersaares** [comment]
Metrics and exporters are associated with an instance of `CollectorRegistry`. By default, the Metrics class registers metrics with `Metrics.DefaultRegistry` and by default, exporters export them from there.

You can create a new registry using `Metrics.NewCustomRegistry()` and register metrics into it via `Metrics.WithCustomRegistry(myRegistry).CreateCounter()`. When creating an exporter, you provide it the instance of the registry to export from, e.g. `app.UseMetricServer(registry: myRegistry)`.

In general, removing metrics is an anti-pattern - your app should expose a static set of metrics. However, it can be quite normal to have different combinations of labels come and go - so if explorer.exe finishes work, RAM usage metrics for explorer.exe go away (but only for explorer.exe). For that purpose you can use `Collector.RemoveLabelled(string[] labels)`.

**Comment by shahabganji** [comment]
@sandersaares 

Thanks for your prompt reply, The `NewCustomRegistry` method works perfect as expected, however, In case of removing metrics I used it like the following:

```cs
 public static readonly Counter AboutCounter = Metrics.WithCustomRegistry(PrometheusRegistries.AlternateRegistry).CreateCounter("shahab", "Some useful information here",
            new CounterConfiguration()
            {
                LabelNames = new[] { "aboutId" }
            }
        );

// omitted code

 AboutCounter.RemoveLabelled("aboutId");
```

When I call the above method I still have the metrics on my scrape end point, unless I provide a correct value. like the following: 

```cs
AboutCounter.RemoveLabelled("1");
```

And one more thing is that I do not have access to the list of all values registered so is there any approach to say remova all metrics with label `aboutId` no matter what the value is?

> In general, removing metrics is an anti-pattern 

Will the metrics reset on every pull from `prometheus`? or removed? Do you mind If I ask for more explanation or articles who could help me through?

Many thanks 🙏

**Comment by sandersaares** [comment]
The [Prometheus website](https://prometheus.io/) has extensive documentation on best practices and might be a good resource to help understand. The [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) discussion group is also moderately active and might be a better forum for extended discussion.

> Will the metrics reset on every pull

Metrics are not affected by reading - they are only changed when your own code makes changes in them (by changing values, adding new metrics or removing some labelled series). Think of them as just variables in your code that are occasionally copied into an external Prometheus database.

> When I call the above method I still have the metrics on my scrape end point, unless I provide a correct value. like the following:

Yes, you need to provide the correct values, not the label names. There are two possibilities here:

* Remember what values you used.
* Use `Collector.GetAllLabelValues()`

Either option can be used to obtain a list of label values, so you can remove the metrics with label values that no longer matter to you.

**Comment by shahabganji** [comment]
Thanks for your time and effort, all solved so I close the issue. Have a good day 😄 👍
