### ISSUE TITLE
Question able to provide older version?

### ISSUE THREAD

**Issue by haarloserhund** [prometheus-net/prometheus-net#144]
Hi,
Version 3.0.3 works for me and all new machines with .Net Framework 4.7.1 .
But I have to manage older machines with .net Framwork < 4.6.1 too. Version 1.3.4 seems to provide me the abillity to do that. The only show stopper is the case sensitive metric type declaration in this version (GAUGE instead of gauge) .

Can you provide me the source code of version 1.3.4 so I can change this and recompile? Would be very nice.

Kind Regards

**Comment by sandersaares** [comment]
The latest version of this library is compatible with .NET Framework 4.6.1, as well (any .NET Standard 2.0 platform works, among which is 4.6.1).

If you want source code for an old version, feel free to explore the Git history to find the relevant commit - it is all in there.

**Comment by JJoe2** [comment]
Would you be prepared to consider adding back .NET 4.5 support using multitargeting?  It looks to me like it would be feasible, and if you're prepared to consider it I'd be happy to create a PR.

From what I see there are the following incompatibilities, which I hope could be addressed using Multitargeting + conditional compilation:

- System.Net.Http reference
- System.ValueTuple dependency (use System.ValueTuple NuGet package?)
- Task.CompletedTask (create a private implementation for .NET 4.5 with conditional compilation)

**Comment by sandersaares** [comment]
No, I am afraid I would not accept a PR to add 4.5 support using multitargeting. This is purely for reasons of keeping the library simple to maintain and develop with limited manpower.
