### ISSUE TITLE
QUESTION: How to support Unicode ( e.g. UTF-8 )

### ISSUE THREAD

**Issue by shahabganji** [prometheus-net/prometheus-net#145]
Dear @sandersaares 

I am using `Prometheus-net` to write metrics to a scrape endpoint, it is worthy to notice that I am using languages that require Unicode support, but on my `/metrics` they are wrong, is there any configuration I need to apply to support Unicode?

Thanks :pray:

**Comment by sandersaares** [comment]
Can you post a code sample that I can use to investigate and more details on how you determine "they are wrong"? I will try reproduce it tomorrow but if you have a simple code sample and exact steps you use to determine correctness, it will help best understand what you are seeing.

**Comment by shahabganji** [comment]
I have a simple ASP.NET Core application in which I tried to create some metrics and I need some other info to be kept as labels in those metrics, here is what I've done:

1. In my `startup` class:

```cs
// omitted code

 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseHttpMetrics();
            app.UseMetricServer("/metrics/alternate", PrometheusRegistries.AlternateRegistry);
            app.UseMetricServer();
           // omitted code
       }
// omitted code
```

2. In my `HomeController`, I try to submit some metrics:

```cs
 public class HomeController : Controller
    {

        public static readonly Counter AboutCounter = 
            Metrics.WithCustomRegistry(PrometheusRegistries.AlternateRegistry)
            .CreateCounter("shahab_total", "Some useful information here",
            new CounterConfiguration()
            {
                LabelNames = new[] { "aboutId" , "message" }
            }
        );

       // omitted code

        private void SaveMetrics(int id, string message)
        {
            AboutCounter.WithLabels($"{id}" , message).Inc();
        }
// omitted code
}
```

In some actions I called the method as the following:
```cs
this.SaveMetrics(1,"سلام");
```

However, when hitting the `/metrics/alternate` url on my endpoint, it's like this:

```
# HELP shahab_total Some useful information here
# TYPE shahab_total counter
shahab_total{aboutId="1",message="Ø³Ù„Ø§Ù…"} 1
```

Any recommendation/suggestion will be appreciated

**Comment by sandersaares** [comment]
Okay, I see the problem. The text actually is UTF-8 but because the `/metrics` endpoint does not say so to the browser, it renders it as ANSI charset. I will correct this.

**Comment by shahabganji** [comment]
Shall I expect a newer version soon? 🙏

**Comment by sandersaares** [comment]
Preview version `3.1.1-pre-006463-cd3cd18` is now up on NuGet (might take 30 min for caches to update). Please let me know if it fixes the issue for you.

**Comment by shahabganji** [comment]
That's awesome! It works as expected. Just one more question Prometheus is set to UTF-8 by default, am I right?

**Comment by sandersaares** [comment]
Yes, UTF-8 is used as the encoding.

**Comment by sandersaares** [comment]
3.1.1 has now been published as stable package.
