### ISSUE TITLE
A bug in histogram sum collection?

### ISSUE THREAD

**Issue by jacostro** [prometheus-net/prometheus-net#147]
Hi,
I'm looking at `Histogram.Child.Observe` method and, if I understand it correctly, there is an error here:
```csharp
public void Observe(double val, long count)
{
    if (double.IsNaN(val))
    {
        return;
    }

    for (int i = 0; i < _upperBounds.Length; i++)
    {
        if (val <= _upperBounds[i])
        {
            _bucketCounts[i].Add(count);
            break;
        }
    }
    _sum.Add(val); // <= shouldn't it be val * count?
    Publish();
}
```
My understanding is that this call should be equivalent to `count` calls to `Observe(val, 1)`, so `_sum` should increase by `val` `count` times.

**Comment by sandersaares** [comment]
I agree with your assessment. This will be fixed shortly. Thanks for reporting

**Comment by sandersaares** [comment]
Preview version `3.1.2-pre-006681-4f8ce09` with this fix is now uploading to nuget.org.

**Comment by jacostro** [comment]
Thank you! That was quick! :-)
