### ISSUE TITLE
Please Consider my implementation

### ISSUE THREAD

**Issue by tellybrown** [prometheus-net/prometheus-net#148]
It seems like this project was converted from java or go or something else because it doesn't seem to follow some .net coding practices.  

1. The use of the ChildBase with a generic seems to have made things overly complex just to get to Inc() or WithLabel(). 
2. The creation of these ThreadSafe classes seems silly to me.  
3. The usage for integrating these objects into a .net project requires a lot of setup and for some reason uses statics.  I'm pretty sure many would consider statics an anti-pattern these days.

What I have done:
1. End-to-end Async is fully implemented.
2. Made it simple to setup your metrics, either by injected properties or by using a builder object.
3. Read/Write locks for thread safety.
4. Created an abstractions library to adhere to MS library organization.
5. Created Hosting and AspNet extensions for simple integration.
6. I use a controller in AspNet and not a kestrel server on a different port.
7. I didn't implement the summary and quantile stuff because I didn't like the idea of just taking what you all did.

I don't really have the time to maintain this project other than just to use it for a proposal to you all.
Thanks
https://github.com/tellybrown/PrometheusCore

**Comment by sandersaares** [comment]
Thank you for the proposal. While ways of doing things better are welcome, it is not obvious to me what exactly might be the valuable aspects to integrate, possibly because I am not sufficiently familiar with your variant of the code to see where any benefits lie. Therefore I take the fallback option of no action here.
