### ISSUE TITLE
500 Errors showing as 200 in /metrics on ASP.NET Core 2.2

### ISSUE THREAD

**Issue by linjmeyer** [prometheus-net/prometheus-net#150]
I have an ASP.NET Core 2.2 project with one controller that works like this:

- Get() method = 200
- Post() method = 500 (throws exception)
- Put() method = 400 (returns bad request)

When testing I am confirming the Post method returns a 500 via CURL, but in /metrics it shows up as a 200 for the ValuesController Post method.

Output of /metrics:

```csharp
http_request_duration_seconds_sum{code="200",method="POST",controller="Values",action="Post"} 0.1010758
http_request_duration_seconds_count{code="200",method="POST",controller="Values",action="Post"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.001"} 0
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.002"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.004"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.008"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.016"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.032"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.064"} 2
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.128"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.256"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="0.512"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="1.024"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="2.048"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="4.096"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="8.192"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="16.384"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="32.768"} 3
http_request_duration_seconds_bucket{code="200",method="POST",controller="Values",action="Post",le="+Inf"} 3
```

Controller:

```csharp
// GET api/values
        [HttpGet()]
        public ActionResult Get()
        {
            Ok();
        }

        [HttpPost()]
        public ActionResult<IEnumerable<string>> Post(string text)
        {
            _exceptionCount++;
            throw new Exception($"I am exception number {_exceptionCount}");
        }

        [HttpPut()]
        public ActionResult Put()
        {
            return BadRequest();
        }
```

Curl example shows 500 error:

```csharp
C02XX041JGH7:~ lin.meyer$ echo '{"text": "Hello **world**!"}' | curl -X POST -d @- --verbose http://localhost:5000/api/values
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> POST /api/values HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 28
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 15 Jul 2019 17:47:06 GMT
< Server: Kestrel
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Startup:
```csharp
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseHttpMetrics(); // Adds basic HTTP metrics to Prometheus /metrics (must be before UseMvc)
            app.UseMetricServer();
            app.UseHealthChecks("/health");
            app.UseMvc();
        }
```

**Comment by linjmeyer** [comment]
Narrowed it down to uncaught exceptions.  I still think its a bug because uncaught exceptions are generally the reason I want to see 500's in the metrics.

Replacing the `throw new exception` with `return StatusCode(500);` and `/metrics` shows the 500 response code.  

When throwing the exception I also found this possibly related stack trace:
```
[12:54:50 ERR] Connection id "0HLO99LEV0RAP", Request id "0HLO99LEV0RAP:00000001": An unhandled exception was thrown by the application.
System.Exception: I am exception number 10
   at brokendotnetcore.Controllers.ValuesController.Post(String text) in /Users/lin.meyer/Repos/brokendotnetcore/Controllers/ValuesController.cs:line 54
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context) in d:\a\1\s\Prometheus.AspNetCore\HttpMetrics\HttpRequestDurationMiddleware.cs:line 28
   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context) in d:\a\1\s\Prometheus.AspNetCore\HttpMetrics\HttpRequestCountMiddleware.cs:line 24
   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context) in d:\a\1\s\Prometheus.AspNetCore\HttpMetrics\HttpInProgressMiddleware.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by sandersaares** [comment]
In a sense, 200 is "right" since ASP.NET Core has not yet decided at that point to make it a 500. This presumably happens higher up the stack, after prometheus-net middleware's job is over. The middleware can see that an exception has been thrown but cannot know how it will be handled by whatever executes after it (or what the result of the handling will be).

That being said, I agree that "right" is not the same as right. Clearly, the request failed and should be reported as such. I can see a few different possible approaches to solve this:

1. Ignore and document it, recommending that exceptions be handled after the middleware. Not ideal, since it is rather surprising behavior and not everyone reads (or follows) documentation recommendations.
1. Add an "exception" label, so you have "status=200,exception=1", enabling you to detect that perhaps the status is not quite final.
1. Try to observe somehow whether it is likely that exceptions will be caught and turned into 500.

When I get a moment, I will explore the feasibility of the latter a bit more - I am not sure if there is a meaningful way to do it.

Meanwhile, I would appreciate any further comments or other input on the topic.

**Comment by linjmeyer** [comment]
Preferably option 3 as in the end I do get a 500 response from the server, but I get the issue that it's a 200 when the middleware runs.  I'll try and find some time to poke around at it as well.  Thanks!

**Comment by mrich316** [comment]
I always use the ExceptionHandlerMiddleware *after* prometheus-net and I don't see this behaviour

```
app.UseMetricServer("/diagnostics/v1/metrics");
app.UseHttpMetrics();
app.UseExceptionHandler(...);
```

And prometheus-net seems to report the proper thing. Do I miss something ?

**Comment by sandersaares** [comment]
If you use an explicit exception handler middleware and configure it after the metrics middleware, that's fine. However, the problem occurs when you either configure the exception handler before metrics or when you do not configure one at all (and let ASP.NET fallback to its default logic, which emits a 500).

After doing some digging in the ASP.NET Core source, I have not found a meaningful way to improve the behavior here, so I will fall back to documenting this aspect. In the end, ASP.NET Core is a pipeline and the nature of the pipelined processing must be understood for actual behavior to match expected behavior. This situation is one of the sufficiently nontrivial ones where it starts to matter.

**Comment by sandersaares** [comment]
I have adjusted the readme to highlight this case. If someone has better ideas, I will happily hear them, though.

**Comment by thoqbk** [comment]
> I always use the ExceptionHandlerMiddleware _after_ prometheus-net and I don't see this behaviour
> 
> ```
> app.UseMetricServer("/diagnostics/v1/metrics");
> app.UseHttpMetrics();
> app.UseExceptionHandler(...);
> ```
> 
> And prometheus-net seems to report the proper thing. Do I miss something ?

@mrich316 I tested with this but all uncaught exceptions will be counted for `/Error`. For example: this is my configuration:

```cs
app.UseHttpMetrics();
app.UseExceptionHandler("/Error");
```

Then all internal server errors (uncaught exceptions) will be the error of /Error instead of the specific APIs. Does this also happen to you?

**Comment by thoqbk** [comment]
@sandersaares I feel this note is not right for `app.UseExceptionHandler("/Error")`:

> NB! Exception handler middleware that changes HTTP response codes must be registered after UseHttpMetrics() in order to ensure that prometheus-net reports the correct HTTP response status code.

https://github.com/prometheus-net/prometheus-net#aspnet-core-http-request-metrics

The [ExceptionHandlerMiddleware](https://github.com/dotnet/aspnetcore/blob/cf29cccf1a2d04e0e86089d4aebd5f7a5768e132/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs) will clean the context and dispatch the request again. If the `UseExceptionHandler("/Error")` is added after `UseRouting()` the result will always be 404 as it doesn't run through the routing step. To make this clearer, do you think we should update it to:


> NB! Exception handler middleware that changes HTTP response codes must be registered after UseHttpMetrics() in order to ensure that prometheus-net reports the correct HTTP response status code. This doesn't apply for `app.UseExceptionHandler(string errorHandlingPath)` which needs to be added before `app.UseRouting()` to be able to re-routing.

I can create a PR if it's good to go.
