### ISSUE TITLE
QUESTION: Apply default labels to all metrics

### ISSUE THREAD

**Issue by ChadJessup** [prometheus-net/prometheus-net#152]
I swear this used to be possible in a prior version (maybe #136 ?), but I can't figure out how to add default labels to any/all metrics defined in the application code.

I'm unable to do this in the prometheus server config itself, so I need to do it in my services.

**Comment by sandersaares** [comment]
The general pattern for adding "global" labels is to do so in the Prometheus server configuration. Adding them directly onto the metrics is not aligned with Prometheus best practices, so the library does not contain a feature specifically for doing this.

If you are convinced you need this, you will need to do so the hard way, by adding the required data individually to the label names and values.

I would like to better understand why you are unable to do this in the Prometheus server configuration. Are you dealing with some unusual restrictions? In general, the server-side configuration is a critical part of Prometheus data collection and an infrastructure where you cannot modify it might not be very long-term maintainable. Rewrite rules are another very common factor defined in those rules and rather critical for non-trivial Prometheus usage.

**Comment by ChadJessup** [comment]
Thanks for responding!
It mainly has to do with corporate structure. Infrastructure pieces are owned by another team with locked down configurations (which, while archaic, is still fairly standard in corporate environments).
When setting up the prom stack, I didn't push back too hard on this because I was able to provide global labels to all metrics before and just have the 'honor_labels' prometheus config option set, but I believe that was the last major version of this library where I was able to get to the Collectors in one place?

Right now, I'm calling `Metrics.DefaultRegistry.CollectAndExportAsTextAsync` and manually injecting these labels with regex, but that's certainly not a good solution.
Me asking hundreds of engineers to remember to add a couple labels to metrics spread across all our services and classes also isn't a sustainable solution.

Not being able to centrally do something like this also means that I can't easily use any of the excellent libraries that add in a ton of useful metrics (`prometheus-net.AspNetCore`, `prometheus-net.DotNetRuntime`, etc).

The big problem I'm having is that prometheus-net wants to strongly enforce the best practices, but the API doesn't allow extensibility for when a user can't follow these practices.

I believe that if I could derive from a couple of the sealed classes, or work off of my own implementations via interfaces, I could solve this in a more elegant manner without the existing API changing in any breaking manner (I might be wrong here, but I'm pretty sure that's the case).

I'd be glad to put in a PR for allowing custom/overriding implementations, if it's something you're interesting in bringing in?

Thanks for your time!

**Comment by sandersaares** [comment]
Thank you for the additional context. I will give it a think and see if I can come up with some improvement. It is indeed true that the library aims to quite strongly enforce best practices, even at the expense of not supporting some use cases (largely to keep the library easy to maintain and avoid the scope creep often seen with open source projects). I do not wish to just open up some classes for overrides but perhaps there is some possibility for enhancement.

**Comment by ChadJessup** [comment]
Thank you! I completely understand the need to minimize surface area and support. Let me know if I can help in anyway, with what you come up with.

**Comment by sandersaares** [comment]
After evaluating the options, I was unable to come with with something lightweight/nondisruptive enough to the library architecture that would also be significantly superior to your approach of regex post-processing.

In use cases that do not follow best practices, I consider it appropriate for the user to pay the cost of not following best practices. For example, by having to do regex post-processing, or by requiring developers remember to always add the relevant missing labels.

Perhaps an internal helper/wrapper library that always enforces the required labels would be useful if you want to avoid post-processing? In the end, I recommend moving to a deployment model that enables the Prometheus configuration to be defined by the operators of the service being collected.
