### ISSUE TITLE
Is it true have to build this project with Visual Studio 2019 plus c# 8.0?

### ISSUE THREAD

**Issue by zscn** [prometheus-net/prometheus-net#159]
When I attempt to build this project with vs2017, the compiler complained about the new C# 8.0 feature is not supported.

Searched online seems it can only be done with vs2019 + c# 8.0 installed(https://stackoverflow.com/questions/56651472/does-c-sharp-8-support-the-net-framework/57020770#57020770)

Is this statement true?

**Comment by sandersaares** [comment]
This statement is true.

**Comment by zscn** [comment]
Thanks for the answer, built successfully with visual studio 2019, worth to mention that have to update vs2019 to 16.3.x (https://stackoverflow.com/questions/58232539/visual-studio-suggests-c-sharp-8-0-features-but-compiler-yields-error)
