### ISSUE TITLE
Am trying to fetch data from prometheus using c#

### ISSUE THREAD

**Issue by joepauly-geon** [prometheus-net/prometheus-net#162]
Can we fetch data from prometheus using any nuget implementation in c#,i would looking to pass a custom query to prometheus.

Custom query: automation_results{testCase="abc"}
The above shows the custom query i would be looking to pass to prometheus,need implement the custom query functionality from c# code.

https://stackoverflow.com/questions/58407331/need-to-fetch-data-from-prometheus-using-c-sharp

**Comment by sandersaares** [comment]
This library is for exporting data from .NET apps to Prometheus. It has no functionality like what you ask about, I fear. [The Prometheus HTTP API](https://prometheus.io/docs/prometheus/latest/querying/api/) is fairly simple and can be used with reasonable success (though not full comfort) using regular HttpClient.

You may also try posting in the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list, maybe someone there has a hint for you that can help you more on your way.

I realize the description of this as a "client" library is confusing in this sense - it does not really let you use the Prometheus API. However, this confusion [appears to be standard Prometheus terminology](https://prometheus.io/docs/instrumenting/writing_clientlibs/).

**Comment by joepauly-geon** [comment]
Thanks @sandersaares .Was able to tweak the code and get the functionality implemented by The Prometheus HTTP API  as you had suggested.
