### ISSUE TITLE
ASP.NET package targetting netcoreapp3.0

### ISSUE THREAD

**Issue by kerams** [prometheus-net/prometheus-net#164]
Hey, would you be OK with creating a netcoreapp3.0 target for Prometheus.AspNetCore? Right now, when I reference the package in a ASP.NET core 3 project, the Microsoft.AspNetCore dependency brings a lot of baggage that pollutes the lock file, even though it's redundant for that particular target. I could send in a PR, it should only be a couple of lines.

**Comment by sandersaares** [comment]
Sure thing, will be published in next version. Thanks @kerams and @JosephWoodward for taking action on this!

**Comment by giggio** [comment]
Was this ever fixed? I just noticed that 3.0 or 3.1 are still not there.

![image](https://user-images.githubusercontent.com/334958/85580954-8e392e00-b612-11ea-98cf-1207d9bb3977.png)

**Comment by giggio** [comment]
Nevermind, I was not looking at the ASPNET Nuget. It is there. Sorry about that. https://www.nuget.org/packages/prometheus-net.AspNetCore
