### ISSUE TITLE
Make constructor of MetricFactory public

### ISSUE THREAD

**Issue by einari** [prometheus-net/prometheus-net#167]
It would be great to have the `MetricFactory` constructor public, so that one can create a custom `CollectorRegistry` that gets passed to the `MetricServer`, giving one the possibility to have potentially multiple servers and and control over the registries. Right now everything is kinda locked down into the default registry, but the API hints at it being possible to do this. 

I will for now use reflection to work around this, but happy to provide a PR for this as well - if agreed that this is a good idea.

**Comment by sandersaares** [comment]
The mechanism to create a new custom registry already exists. The `Metrics` class is the intended mechanism to interact with the metrics creation API, so you'll find all the relevant methods there.

`Metrics.NewCustomRegistry()` will create a new empty registry. `Metrics.WithCustomRegistry()` will create a `MetricFactory` that can create the collectors in that registry. You can pass this registry to the metric server types to export data from the registry.

Do these methods solve your needs or is there anything missing?

**Comment by sandersaares** [comment]
I will close this for now but if anything remains unclear or if I misunderstood your proposal, please leave a comment or open another issue.
