### ISSUE TITLE
[Question] Label values must be of same length as label names?

### ISSUE THREAD

**Issue by Memhave** [prometheus-net/prometheus-net#169]
Hey,

Im encountering this error when attempting to push metrics to the prom push gateway: 
![image](https://user-images.githubusercontent.com/8819474/68323214-48504980-00c5-11ea-920b-8d70ef9fc5b7.png)

I wasnt aware of this restriction and it seems rather odd?  Is there some documentation that I've missed? :D

**Comment by Memhave** [comment]
It looks like I simply misunderstood the error message, the length of the label _array_ must be of the same length. 

Closed.

**Comment by sandersaares** [comment]
Yeah that's a rather bad error message you ran into! I will do a review of the error messages to try improve understandability.
