### ISSUE TITLE
Configure DotNetStats.Register for startup performance?

### ISSUE THREAD

**Issue by bdrupieski** [prometheus-net/prometheus-net#170]
I have a feature request related to performance.

The `Metrics` static constructor calls `DotNetStats.Register(DefaultRegistry);` here: https://github.com/prometheus-net/prometheus-net/blob/252e89c7910e98173de6bfcda8798e806a558031/Prometheus.NetStandard/Metrics.cs#L86

I don't use these metrics and immediately call `SuppressDefaultMetrics`, which suppresses the default metrics by building a new registry.

From profiling my application I've found initializing and suppressing these default metrics can add 50-100 ms to application startup. When starting and stopping constantly, like from making small tweaks locally, or in something like Azure Functions, this time starts to add up. It's frustrating because the time is spent on a feature I don't use and am trying to disable. 

Is it possible to introduce configuration so that we do not call `DotNetStats.Register` in the first place, while still keeping it on by default so that it's backwards compatible for existing usages that expect it to be run?

**Comment by sandersaares** [comment]
Sure, why not. Can you share your benchmark code? I would be happy to integrate some startup benchmark into the project.
