### ISSUE TITLE
Response OutputStream being Disposed can cause unexpected errors

### ISSUE THREAD

**Issue by zitcomdev** [prometheus-net/prometheus-net#171]
In MetricServer.cs, the response output stream is explicitly being disposed. What is the reason for this ? 
It causes unexpected errors if you access the response output stream within other middlewares.

If there is a valid reason, shouldn't it also be disposed in case of exceptions ?

**Comment by sandersaares** [comment]
I assume this issue refers to the ASP.NET Core exporter middleware, implemented in `MetricServerMiddleware.cs`, which has similar code to `MetricServer.cs`. The latter is used for the old HttpListener based implementation, so does not experience any middleware interactions.

Indeed, I do not think there is a real need to dispose of the output stream in the ASP.NET Core middlware. I will adjust the code to not do that.

> If there is a valid reason, shouldn't it also be disposed in case of exceptions ?
The StreamWriter did that but as you point out there's really no reason to dispose of the output stream, so I will adjust that case, as well.
