### ISSUE TITLE
Endpoint routing

### ISSUE THREAD

**Issue by chuseman** [prometheus-net/prometheus-net#172]
Going forward with ASP.NET Core 3.0, it looks like content-serving middleware should use [endpoint routing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#endpoint-routing-differences-from-earlier-versions-of-routing).

Take [Health checks](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0) for example: they're now registered via [MapHealthChecks](https://github.com/aspnet/AspNetCore/blob/658b37d2bd3b0da2c07e25b53fa5c97ce8d656d3/src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs) instead of `UseHealthChecks` like was recommended in ASP.NET Core 2.2.

This would also allow for removal of the port parameter, as implementers could instead specify a hostname (or port) via the [RequireHost](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.routingendpointconventionbuilderextensions.requirehost?view=aspnetcore-3.0) extension method on the `IEndpointConventionBuilder` that the new `MapMetrics` extension method would return.

If there's interest, I'd be happy to contribute these changes.

**Comment by mashbrno** [comment]
Sure there is! I just upgraded my project and found that Prometheus stopped working.

**Comment by sandersaares** [comment]
Sure, I would be interested to understand the details of this. In testing prometheus-net with ASP.NET Core 3 I have not found situations where the default routing stops working (even if endpoint routing is used) but this testing has not been very thorough and no issues have been reported with reproducible errors related to ASP.NET Core 3.

If you can outline the exact scenario where prometheus-net fails to work as expected and provide either a description of what would be needed to correct it or a PR, that would definitely be appreciated.

**Comment by kerams** [comment]
When I used a custom port in `UseMetricServer`, I could not get a response from the new edpoint. I only had a quick look, so it could have been my fault...

**Comment by mashbrno** [comment]
Guys, can you please share sample of `Startup.cs` configuration for asp.net core 3? Especially @sandersaares the working one with endpoint routing),

**Comment by chuseman** [comment]
> If you can outline the exact scenario where prometheus-net fails to work as expected and provide either a description of what would be needed to correct it or a PR, that would definitely be appreciated.

I don't think it is necessarily broken using middleware directly. I believe endpoint routing was an effort at a better design with configuration that is easier to reason about.

Exposing `IEndpointConventionBuilder` also makes things more extensible for the end user -- where they can handle tying it to a specific host name/port (or other restrictions) themselves.

So I'd think of this as just a design improvement, not a bug fix.
