### ISSUE TITLE
Question, Does metrics data  have a life time in memory?

### ISSUE THREAD

**Issue by srm2020** [prometheus-net/prometheus-net#176]
Could someone please Indicate if the metrics data have a life time - so it is cleared after a period of time - or metrics data continue   accumulating  and filling  computer memory –may be lead to system crash- ?
Thanks.

**Comment by sandersaares** [comment]
Each collector instance consumes a fixed amount of memory over its lifetime. The memory usage depends on the total number of collectors and their labeled instances.

So if you do `Metrics.RegisterCounter()` (or any other collector) then this will allocate a certain amount of memory. This amount will not increase.

If you do `myCounter.WithLabels("aaaa")` then this will increase the RAM usage for each unique combination of labels.

As long as you do not create new label values at runtime, prometheus-net memory usage will stay constant. If you do create new label values at runtime, memory use will increase for each unique combination.

Does this answer your question?

**Comment by srm2020** [comment]
Dear Mr. Sandersaares
Thank You very much for Explanations.
