### ISSUE TITLE
No RouteData when using custom exception handler

### ISSUE THREAD

**Issue by ivonin** [prometheus-net/prometheus-net#177]
We have a problem with prometheus-net reporting empty `controller` and `action` labels when the exception occurs:

```
http_request_duration_seconds_count{code="500",method="GET",controller="",action=""}
...
```

We do have a custom exception handler set up:

```csharp
app.UseHttpMetrics();
app.UseMetricServer();
// ....
app.UseExceptionHandler(errorApp =>
{
    errorApp.UseMiddleware<ExceptionHandlerMiddleware>();	
});
```

The root of the problem seems to be [in these lines in the ExceptionHandlerMiddleware class](https://source.dot.net/#Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs,150):

```csharp
// An endpoint may have already been set. Since we're going to re-invoke the middleware pipeline we need to reset
// the endpoint and route values to ensure things are re-calculated.
context.SetEndpoint(endpoint: null);
var routeValuesFeature = context.Features.Get<IRouteValuesFeature>();
routeValuesFeature?.RouteValues?.Clear();
```

I presume that this change was made based on [this issue](https://github.com/aspnet/AspNetCore/issues/11233#issuecomment-502309428) and made it to ASP.NET Core 3.0 that we use.

Is there a workaround? Can it probably be fixed via different order of middleware registrations?

**Comment by kerams** [comment]
As a workaround, I think you could place a custom middleware just before `errorApp.UseMiddleware<ExceptionHandlerMiddleware>()` which would store route values if set, invoke next (`ExceptionHandlerMiddleware`) and then restore those values if the exception handler removed them (and if you're sure you won't be affected by the issue you linked).

I'm doing something similar where I manually fill in route values on `HttpRequest` since I don't use MVC but am interested in http metrics for individual route handlers.

**Comment by sandersaares** [comment]
@ivonin please post a repository containing an executable sample app that demonstrates the issue.

**Comment by ivonin** [comment]
@sandersaares sure, here it is: https://github.com/ivonin/Prometheus-Net-Issue177

The last commit adds the custom exception handling that leads to missing route data in metrics, the starting commit is the default ASP.NET Core Web app.

**Comment by sandersaares** [comment]
Thanks a lot, having that example was very useful! I agree with your assessment of the primary cause of the problem.

To address this scenario, in prometheus-net v3.4.0, you will be able to call `app.UseRouteDataForHttpMetrics()` immediately after `app.UseRouting()` to capture the route data for metrics. Any changes to route data after this call will not affect the metrics.

This change also enables per-route labeling for the "in progress HTTP requests" metric, which previously lacked route-specific labels (or indeed any labels).

A preview build of v3.4.0 is currently uploading to NuGet.org. Please confirm whether calling `app.UseRouteDataForHttpMetrics()` after `app.UseRouting()` appears to solve your problem when using this version.

**Comment by sandersaares** [comment]
Updated preview build of v3.4.0 is uploading now. Just call `UseHttpMetrics` after `UseRouting` and it will persist the route data. Any later changes to route data (e.g. in exception handlers) will not affect metrics.

Please let me know if this appears to solve your problem.

**Comment by ivonin** [comment]
@sandersaares the 3.4.0 version does solve the issue with the controller and action values after changing the order of middleware registration, thanks.

I now have problems with error code not being used (my 500 errors are counted as 200 in the metrics). This probably also has something to do with custom error handler, I'll look into it and maybe create another issue. Feel free to point me in the right direction if this is a known issue though.

**Comment by ivonin** [comment]
Yes, everything works fine, thanks!

The problem with error codes as due to incorrect order of middleware registrations.
