### ISSUE TITLE
Access denied error when creating new Metrics Server on azure app service

### ISSUE THREAD

**Issue by vanitakolukuluri** [prometheus-net/prometheus-net#183]
When I am trying use this library and create metric server like below
var server = new MetricServer(80, "metrics/", null, false)

It is giving access denied error. I got this working locally by using "netsh" tool and issuing permissions for the user. However, my application will be deployed as azure app service. It is giving same error there as well. How can this be fixed for azure app service. Is this a known issue when using this library with azure app service. Your help is greatly appreciated.

[HttpListenerException (0x5): Access is denied]
   System.Net.HttpListener.SetupV2Config() +434
   System.Net.HttpListener.Start() +366
   Prometheus.MetricServer.StartServer(CancellationToken cancel) +66
   Prometheus.MetricHandler.Start() +56
   TeleTracking.Web.WebApiApplication.Application_Start() +1287

[HttpException (0x80004005): Access is denied]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +517
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +185
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Access is denied]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714

**Comment by sandersaares** [comment]
Please share a complete sample project that demonstrates this issue.

**Comment by vanitakolukuluri** [comment]
Sorry I won't be able to upload the project. It's not my personal project. We are using .NetFramework4.6.2. I am trying to publish via standalone HTTP handler. On my local machine (Windows) It gave access denied when I tried as mentioned in readme but the given workaround "netsh http add urlacl url=http://+:1234/metrics user=DOMAIN\user" took care of the issue.Now the problem is when I deploy my application as an app service I am getting same access denied exception. Azure app service doesnot let you run netsh command.

**Comment by sandersaares** [comment]
You don't need to upload your real project, just a sample project that matches the design of your real project would do.

While I can guess what is happening, it is hard for me to offer a solution if I do not know how your solution works internally. Having a sample project to use as a reference would be helpful in assisting you.

**Comment by vanitakolukuluri** [comment]
Sorry for the delay. Please  find the attached sample project. It is deployed in azure. You can access using and see the access denied error. I used port 80 but I do get same error any port that I use. Azure app service opens only 80 and 443. So that's why I was using 80.

https://prometheussampleapp20200106111135.azurewebsites.net/

**Comment by vanitakolukuluri** [comment]
The project size is 55 MB. So it was not letting me attach. Let me see If I can upload to git and give that url

**Comment by vanitakolukuluri** [comment]
Here is the code https://github.com/vanitakolukuluri/PrometheusSampleApp

**Comment by vanitakolukuluri** [comment]
@sandersaares  - Is this known issue. Can you please shed some light?

**Comment by sandersaares** [comment]
Thanks for providing the sample project! That helps clarify matters.

Indeed, what you see is a side-effect of a limitation in Azure web sites. Or perhaps it would be correct to say that it is a side-effect of how the `MetricServer` class works - the mechanism it uses is not ideal for classic ASP.NET situations.

To help get past this, I have added a new mechanism that allows you to easily expose metrics from an ASP.NET application, without having to use `MetricServer`. Please see the new chapter in the readme for usage instructions:  https://github.com/prometheus-net/prometheus-net#aspnet-web-api-exporter

Currently, this feature is available in a prerelease NuGet package, version `3.5.0-pre-000098-f9cb93e`. Please let me know if it works for you satisfactorily.

**Comment by sandersaares** [comment]
3.5.0 is now uploading. I will close this issue given that there has been no further feedback. Please feel free to leave another comment or open a new issue if you feel something is not right.
