### ISSUE TITLE
Force push for MetricPusher

### ISSUE THREAD

**Issue by talenor** [prometheus-net/prometheus-net#185]
It would be good to add force push support for MetricPusher.
It's useful in a case when we have a big push interval and integrate MetricPusher into a desktop application. If we close the app we could lose some metrics.

**Comment by sandersaares** [comment]
The metric pusher is designed to do a forced final push when the pusher is disposed of. If you dispose of the object during shutdown, you should be able to avoid data loss.

Does this satisfy your needs? If not, please explain in detail how/when you would like to be able to initiate a force push and how it would tie into the app closing workflow that you have in mind.

**Comment by sandersaares** [comment]
Given that there has been no further comments for many weeks, I will close this issue and assume the case is resolved. If not, please leave a comment or open a new issue.
