### ISSUE TITLE
Histogram - Timer

### ISSUE THREAD

**Issue by matt-lethargic** [prometheus-net/prometheus-net#188]
Hi, this is probably a feature request.

I'm struggling with the using Histograms and the Timer. I've create an abstraction around the Prometheus.Net client so that I can inject an instance of the abstracted interface and not reference Prometheus.net in all of my Domain and Adapter projects.

Is there a way I can just record an elapsed time against a histogram or would this need to be new functionality?

Thanks

**Comment by sandersaares** [comment]
I am having difficulty understanding what exactly you are asking.

Prometheus-net includes some timer extensions for `IObservable` (histogram/summary). Indeed, if you do not use the prometheus-net interfaces/classes then this extension will not be very useful for you. If you wish to have the same functionality with some other interfaces/classes then I suggest replicating the functionality you need, using your custom interfaces/classes.

This sounds like a not very helpful answer so possibly I misunderstand the question. Please clarify if so.

**Comment by sandersaares** [comment]
Given that there has been no further comments for many weeks, I will close this issue and assume the question is answered. If not, please leave a comment or open a new issue.
