### ISSUE TITLE
Allow scoped metrics

### ISSUE THREAD

**Issue by asquithea** [prometheus-net/prometheus-net#193]
My project has a use-case where we want to create metrics with detailed labels that are exposed for a limited period of time.

For context, imagine that a service is streaming segments of data to a broker using a GUID to identify each segment. Each segment might last for anything from 1 minute to 1 day, but over time there will be a lot of unique segment GUIDs. If we expose the GUID as a segment_id label, we can do segment-specific fault analysis correlated with other systems connected to the broker. There may be several concurrently-active segments.

Having an ever-increasing number of label combinations is undesirable, so using earlier versions of prometheus-net (1.x) we created a custom registry for each segment, and aggregated them together as children of a custom `ICollectorRegistry`. As each segment ends, its registry is unhooked. This means that each time the metrics server is polled, it only sees metrics for active streams of data.

This was pretty useful, but we can't do this dynamic registry approach with the current API: there is no abstraction for `CollectorRegistry` and the class is sealed. If an `ICollectorRegistry` were re-introduced, that would likely be sufficient, but I'm open to any other suggestions.

**Comment by sandersaares** [comment]
The pattern I would recommend for this would be to unregister the metric instances when your segment is disposed of.

That is, if you create a metric instance as `myMetric.WithLabels("aaa", "bbb")` then you can remove it later with `myMetric.RemoveLabelled("aaa", "bbb")`.

This should enable you to clean up obsolete metric instances. Does this functionality provide what you need?

**Comment by sandersaares** [comment]
I have added IDisposable to the labeled child metrics to better signal the availability of this functionality (equivalent to `child.Remove()` or `metric.RemoveLabelled()`).

**Comment by sandersaares** [comment]
Given that there has been no further comments for many weeks, I will close this issue and assume the case is resolved. If not, please leave a comment or open a new issue.
