### ISSUE TITLE
Actually target netstandard?

### ISSUE THREAD

**Issue by RheaAyase** [prometheus-net/prometheus-net#194]
Hi all,

I don't know if I'm missing something but prometheus-net [nuget package](https://www.nuget.org/packages/prometheus-net/) seems to target only .NET Framework 4.61

More funny is that somehow `prometheus-net.AspNetCore` which does target .NET Standard seems to have `prometheus.net` as a dependency, while that one does not target .NET Standard.

If I'm missing something please explain how can one use these packages in .NET Core (on Linux)

**Comment by RheaAyase** [comment]
Or perhaps the word target is not correct in this context, it simply does not list net standard.

**Comment by sungam3r** [comment]
Interesting. Nuget package content seems normal:
![image](https://user-images.githubusercontent.com/21261007/73449015-44099480-4373-11ea-9247-55fec8350119.png)

**Comment by sungam3r** [comment]
I think `prometheus-net.nuspec` file should have explicit dependencies groups for all targets.

**Comment by sungam3r** [comment]
I checked it. If you do not use the nuspec file, but rely on `GeneratePackageOnBuild` property in csproj, then all dependency groups will be filled up. So I think we should modify nuspec. @sandersaares what do you think?

**Comment by RheaAyase** [comment]
That's an interesting gotcha, I've never seen something like this happen.
Thanks for looking into it :D

**Comment by sandersaares** [comment]
What exactly is the problem you are experiencing? Are you getting some error when attempting to reference the package?

**Comment by sungam3r** [comment]
I think that the problem is that the [nuget page](https://www.nuget.org/packages/prometheus-net/) misleads the reader (it lists only net461 target):
![изображение](https://user-images.githubusercontent.com/21261007/74101799-b5ed9500-4b4e-11ea-8c52-ccac464cf71e.png)

**Comment by sandersaares** [comment]
I see. Okay - while I don't think relying on the dependencies list to determine supported frameworks is really the intended usage of that list, I suppose it won't hurt to be more explicit and list them all, though, to avoid confusion on this topic.

**Comment by sandersaares** [comment]
![image](https://user-images.githubusercontent.com/9914262/74102828-d66a1f00-4b4f-11ea-981d-e318e6d6ae9e.png)

There we go, I hope that helps!
