### ISSUE TITLE
Can we get all currently registered Collectors and their values?

### ISSUE THREAD

**Issue by ChristianSauer** [prometheus-net/prometheus-net#197]
Ok, that sounds dumb but I would like to collect all Metrics and transform them into the Actuator Metrics Format - this would enable some nice integration with Tools like Spring Boot Admin.
Unfortunately, the only Public API I have found returns only the text. I can parse this, but it would be nice if I could avoid that. So is there a way to get the Metrics and their values? I have seen no obivous way to add an interface or so.

**Comment by sandersaares** [comment]
There is indeed no API for this. The prometheus-net library is designed specifically to export data in the Prometheus text format and provides minimal facilities for runtime inspection or export in other formats.

If you wish to transform the metrics to another format, parsing the text is probably the easiest method to accomplish that.

**Comment by sandersaares** [comment]
Given that there has been no further comments for many weeks, I will close this issue and assume the question is answered. If not, please leave a comment or open a new issue.
