### ISSUE TITLE
Callback for when /metrics endpoint is called ?

### ISSUE THREAD

**Issue by Stefama2020** [prometheus-net/prometheus-net#198]
I have a gauge returning a time-window related performance value (imagine something like call per minute) and while I'm updating it when the tracked event occurs, I realized that I'd also need to update it when the /metrics endpoint is called. Can you suggest a way to achieve it? Any callback available for something like this?

**Comment by sandersaares** [comment]
Sure thing. This is already supported. See https://github.com/prometheus-net/prometheus-net#just-in-time-updates

**Comment by sandersaares** [comment]
Given that there has been no further comments for many weeks, I will close this issue and assume the case is resolved. If not, please leave a comment or open a new issue.
