### ISSUE TITLE
Possibility to add raw metrics

### ISSUE THREAD

**Issue by mookid8000** [prometheus-net/prometheus-net#199]
Hello there,

In an effort to collect metrics from a couple of continuously running Azure webjobs, I am experimenting with having each webjob start a `MetricPusher` pointing to the web site they're running under.

With this approach, I am now successfully receiving POSTs to the route `/api/job/<job-name>` with raw metrics, e.g. like
```
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2
# HELP process_open_handles Number of open handles
# TYPE process_open_handles gauge
process_open_handles 845
# HELP process_num_threads Total number of threads
# TYPE process_num_threads gauge
process_num_threads 30
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2203979939840
# HELP process_working_set_bytes Process working set
# TYPE process_working_set_bytes gauge
process_working_set_bytes 65929216
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1583150732.87702
# HELP dotnet_collection_count_total GC collection count
# TYPE dotnet_collection_count_total counter
dotnet_collection_count_total{generation="2"} 1
dotnet_collection_count_total{generation="0"} 8
dotnet_collection_count_total{generation="1"} 2
# HELP dotnet_total_memory_bytes Total known allocated memory
# TYPE dotnet_total_memory_bytes gauge
dotnet_total_memory_bytes 3458992
# HELP process_private_memory_bytes Process private memory size
# TYPE process_private_memory_bytes gauge
process_private_memory_bytes 38252544
```

Is there a way I can expose these in my API's metrics endpoint, thus effectively working as a combined normal web application combined with push gateway functionality?

To me, it seems like having something similar to `Metrics.DefaultRegistry.CollectAndExportAsTextAsync(target)` – only working in reverse (turning text into appropriate `Collector`s) – would do the trick. 😁

E.g. so I could "import" raw metrics text pushed to my endpoint by installing an ASP.NET handler that would look somewhat like this:
```
endpoint.MapPost("/api/job/{*job}", async context =>
{
    var request = context.Request;
    var response = context.Response;

    if (!request.RouteValues.TryGetValue("job", out var job))
    {
        response.StatusCode = (int)HttpStatusCode.BadRequest;
        await response.WriteAsync("Please POST the job name as a route value, e.g. like /api/job/<job-name>");
        return;
    }
    
    // would I use "job" here somehow?

    // this method does not exist :)
    await Metrics.DefaultRegistry.ImportFromTextAsync(request.Body);

    response.StatusCode = 200;
    await response.WriteAsync("OK");
});

```
(`ImportFromTextAsync` above being a method that does not exist on `CollectorRegistry`.....)

Does this sound crazy? Or would it be doable somehow?

If this sounds feasible, I would be happy to provide the necessary PRs to make this work. 🙂

**Comment by sandersaares** [comment]
If I understand your description right, your use case should be perfectly served by https://github.com/prometheus/pushgateway. You can use it to aggregate multiple pushed metric sets into a single whole. I recommend you use it.

This functionality is out of scope for prometheus-net.

**Comment by mookid8000** [comment]
> If I understand your description right, your use case should be perfectly served by https://github.com/prometheus/pushgateway.

Indeed it is – but for Azure-hosted services that would require me to host the pushgateway in a place where they can access it with a public endpoint somewhere, which might not be possible on the big internet.

I am totally aware that what I am asking as actually for a pushgateway-type of functionality embedded in the .NET driver.

But I can definitely understand why you might consider this out of scope for prometheus-net. 😐

**Comment by sandersaares** [comment]
Indeed so. I'll mark the question closed then.

**Comment by mookid8000** [comment]
Ok. Do you have any ideas on how to collect metrics from Azure-hosted webjobs then?

**Comment by sandersaares** [comment]
I am afraid I am not sufficiently familiar with Azure-hosted webjobs to comment. Possibly you might find some suggestions on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
