### ISSUE TITLE
system.security.principal.windows 4.5.1 not found dep.json

### ISSUE THREAD

**Issue by amalkurup89** [prometheus-net/prometheus-net#201]
Facing an error while deploy dotnet core 2.1 application, while exposing HTTP metrics using below method call 

app.UseHttpMetrics();

**Error Message :** "system.security.principal.windows 4.5.1 not found dep.json"

But, if I include only app.useMetricServer() , the application is deployed successfully and metrics are also exposed

Please guide on this

**Comment by sandersaares** [comment]
I am unable to reproduce this error.

Please provide exact steps and a zipped sample project that can be used to reproduce this issue.

**Comment by sandersaares** [comment]
I am closing this due to no response for a long time. Feel free to open a new issue if you continue to need help with this.
