### ISSUE TITLE
Is it possible to change the default RequestDuration's options?

### ISSUE THREAD

**Issue by robertocpsilva1** [prometheus-net/prometheus-net#204]
Is there a way to customize the default histogram used by the `UseHttpMetrics` middleware?
I'd like to have custom buckets and an extra label for the request route.
I couldn't find any documentation to do this. Let me know if I've missed it.

Thanks

**Comment by martinhansen** [comment]
I don't think so, since they sealed their classes. I would like the same options too, as it's impossible to have multiple applications being scraped by the same prometheus instance, since the histograms have the same name. Best guess is to make the changes you like, and make a pull request. (im thinking about doing so if i dont find a solution myself). I think the files are here:

https://github.com/prometheus-net/prometheus-net/tree/master/Prometheus.AspNetCore/HttpMetrics

**Comment by cmannix** [comment]
Hi - you should be able to customise the options using the provided `UseHttpMetrics` extension method, unless I'm misunderstanding your question. It provides overloads allowing you to either specify the options object as a whole, or customise it as needed:

```
app.UseHttpMetrics(opt => {
                opt.RequestDuration.Histogram = Metrics.CreateHistogram("app_specific_name", "app_specific_help",
                new HistogramConfiguration
                {
                    Buckets = Histogram.ExponentialBuckets(0.001, 2, 16),
                    LabelNames = HttpRequestLabelNames.All
                });
            });
```
Which provides this in the metric output:
```
# HELP app_specific_name app_specific_help
# TYPE app_specific_name histogram
```

Does that solve the issue you were having?

**Comment by robertocpsilva1** [comment]
That was it, thank you!

**Comment by robertocpsilva1** [comment]
It would probably be a good idea to not create an of the metrics objects if you pass options in so that you can reuse the names

**Comment by Jeff-Tian** [comment]
> Hi - you should be able to customise the options using the provided `UseHttpMetrics` extension method, unless I'm misunderstanding your question. It provides overloads allowing you to either specify the options object as a whole, or customise it as needed:
> 
> ```
> app.UseHttpMetrics(opt => {
>                 opt.RequestDuration.Histogram = Metrics.CreateHistogram("app_specific_name", "app_specific_help",
>                 new HistogramConfiguration
>                 {
>                     Buckets = Histogram.ExponentialBuckets(0.001, 2, 16),
>                     LabelNames = HttpRequestLabelNames.All
>                 });
>             });
> ```
> 
> Which provides this in the metric output:
> 
> ```
> # HELP app_specific_name app_specific_help
> # TYPE app_specific_name histogram
> ```
> 
> Does that solve the issue you were having?

That works like a charm!

However, it won't break the customLabel, which means the following can't work both:

```csharp
app.UseHttpMetrics(opt => {
                opt.RequestDuration.Histogram = Metrics.CreateHistogram("app_specific_name", "app_specific_help",
                new HistogramConfiguration
                {
                    Buckets = Histogram.ExponentialBuckets(0.001, 2, 16),
                    LabelNames = HttpRequestLabelNames.All
                });
                opt.AddCustomLabel("xxx", _ => "yyy");
            });
```

The above code will raise an exception: 

```
Unhandled exception","@i":"f80f533c","@l":"Fatal","@x":"System.ArgumentException: Provided custom HTTP request metric instance for HttpRequestDurationMiddleware is missing required labels: xxx
```

How to fix that? Thanks in advance!

**Comment by Jeff-Tian** [comment]
Finally fixed the above issue by

```csharp
app.UseHttpMetrics(opt => {
                opt.RequestDuration.Histogram = Metrics.CreateHistogram("app_specific_name", "app_specific_help",
                new HistogramConfiguration
                {
                    Buckets = Histogram.ExponentialBuckets(0.001, 2, 16),
                    LabelNames = HttpRequestLabelNames.All.concat(new [] {"xxx"}).toArray()
                });

                opt.AddCustomLabel("xxx", _ => "yyy");
            });

```
