### ISSUE TITLE
Delay first values publication while publishing 0 for labeled counters

### ISSUE THREAD

**Issue by alexvaut** [prometheus-net/prometheus-net#206]
When publishing a counter without a label, the initial published value is 0.
When publishing a counter with a label, the initial published value is the same as the first published value from the client. 
=> this is causing an issue when using `increase(metric)` in PromQL since there is no delta between the initial value and the first value which are the same.

To solve this, I'm thinking about a mechanism that would publish 0 as soon as the first value is published. Store the published values from the client until the system is scrapped and then publish all the stored values and go back in normal mode. 

It would require a scrapTimeOut or maxStoreSize value in case the scrap is not done for some reasons.

One of the drawback of this solution is the delay that it adds between first values publication from client and scrapping from prometheus. But I can live with that.

**Comment by sandersaares** [comment]
> When publishing a counter with a label, the initial published value is the same as the first published value from the client.

The default behavior for labelled counters is to publish a value of 0 as soon as the label value is known. This avoids exactly the problem you describe.

If the behavior you experience is different, please explain exactly how to reproduce the issue. It would be best if you could provide a sample project that demonstrates the problematic behavior (a situation where the 0 is not published when the label value is known).

**Comment by sandersaares** [comment]
I am closing this due to no response for a long time. Feel free to open a new issue if you continue to need help with this.
