### ISSUE TITLE
Metrics with HealthChecks

### ISSUE THREAD

**Issue by RPrzepio** [prometheus-net/prometheus-net#209]
I wanted to send HealthChecks to Prometheus and have nice dashboard in Grafana with section "health".
Something similar to the one created for app-metrics 
https://grafana.com/grafana/dashboards/2204

Is it possible to achieve it? Or better just to create another metrics and forget about health-checks?
I just started learning how to configure and use metrics, so sorry for maybe strange questions :)

**Comment by sandersaares** [comment]
Publishing HealthChecks metrics to Prometheus is a completely valid use case, sure. There is no built-in integration that I am aware of at the moment. However, it is possible someone has made such an integration and I am simply not aware of it.

**Comment by sandersaares** [comment]
Oh looks like someone is on the case! #203

**Comment by sandersaares** [comment]
This feature is now available in preview NuGet package version 3.6.0-pre-000129-bd91778. Please give it a try. If no problems are reported within a few days, I will publish this build as stable package.

**Comment by sandersaares** [comment]
3.6.0 with the fix is now published. I'll mark this as closed - please feel free to open a new issue for any additional requests/bugreports.

**Comment by RainingNight** [comment]
@RPrzepio Can you share you dashboard json? Thanks! Like [healthchecks dashboard](https://github.com/prometheus-net/grafana-dashboards/issues/3).
