### ISSUE TITLE
Prometheus.KestrelMetricServer.StartServer Error

### ISSUE THREAD

**Issue by Jarh000** [prometheus-net/prometheus-net#210]
Hi,

When i try to start Prometheus.KestrelMetricServer it show following message.

Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

but Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0 it doenst exist. 

What do I need to do this work?

thanks

**Comment by kvakulo** [comment]
I just ran into the same problem when upgrading from 3.3.0 to 3.5.0 of `prometheus-net.AspNetCore` used in a console app.

The solution was to add a framework reference in the project file:

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="3.5.0" />
  </ItemGroup>
```

**Comment by sandersaares** [comment]
Can you provide a sample project that reproduces the issue? I would like to publish NuGet packages that do not require any manual work like that but so far I have been unable to reproduce the issue on my own.

**Comment by kvakulo** [comment]
Hi @sandersaares,

I've created a minimal samle project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="prometheus-net.AspNetCore" Version="3.5.0" />
  </ItemGroup>
</Project>
```

with a single class:

```c#
using Prometheus;

class Program
{
    static void Main(string[] args)
    {
        new KestrelMetricServer(12345).Start();
    }
}
```

When executing this code, I get the following error:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Prometheus.KestrelMetricServer.StartServer(CancellationToken cancel)
   at Prometheus.MetricHandler.Start()
   at Program.Main(String[] args) in C:\...\Program.cs:line 7
```

However after adding the framework reference to `Microsoft.AspNetCore.App` it starts to work:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="3.5.0" />
  </ItemGroup>
</Project>
```

Please let me know if you need any further info 😄

**Comment by sandersaares** [comment]
I see. The problem is that your project file is using the .NET Core SDK and not the ASP.NET Core SDK. Microsoft has changed how the SDK tooling works so that the correct ASP.NET Core references are only added when you use the correct SDK.

You need to change from this:

```
<Project Sdk="Microsoft.NET.Sdk">
```

To this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
```

This is far from the only problem that occurs when you don't have that `.Web`. Unfortunately it can sort of sneak up on you if you just want to create a console app.

**Comment by kvakulo** [comment]
Thanks for your answer @sandersaares!

I can confirm that it works without the framework reference when using `Microsoft.NET.Sdk.Web` :+1:

After changing the SDK I started to get this error when running the console application from Visual Studio:
![image](https://user-images.githubusercontent.com/359614/84123843-afa6f100-aa3a-11ea-886b-48a911b3cea0.png)

This could be solved by adjusting `launchSettings.json` and setting `"launchBrowser": false`.

**Comment by sandersaares** [comment]
Alright. Let's consider this closed for now then. If there is still any problem for OP, please leave a comment or open a new issue.
