### ISSUE TITLE
gRPC metrics

### ISSUE THREAD

**Issue by Daniel15** [prometheus-net/prometheus-net#211]
I noticed that this project has some standard HTTP metrics (via `UseHttpMetrics`), but would it be possible to add gRPC metrics too? For example, I'd like to see the number of calls to each of my gRPC services. Probably something like the `http_requests_received_total` counter but with service and method name instead of controller and action.

**Comment by Daniel15** [comment]
Looked into the code and the gRPC server adds some metadata to the endpoint which specifies the service and method name. This is what I came up with:

```csharp
public class PrometheusGrpcMetricsMiddleware
{
	private readonly RequestDelegate _next;

	private readonly Counter _receivedRequests = Metrics.CreateCounter(
		"grpc_requests_received_total", 
		"Number of received gRPC requests",
		new CounterConfiguration
		{
			LabelNames = new [] { "service", "method" }
		}
	);

	public PrometheusGrpcMetricsMiddleware(RequestDelegate next)
	{
		_next = next;
	}

	public async Task Invoke(HttpContext context)
	{
		try
		{
			await _next(context);
		}
		finally
		{
			LogRequest(context);
		}
	}

	private void LogRequest(HttpContext context)
	{
		var metadata = context.GetEndpoint().Metadata.GetMetadata<GrpcMethodMetadata>();
		var method = metadata?.Method;
		if (method == null)
		{
			return;
		}

		_receivedRequests.WithLabels(method.ServiceName, method.Name).Inc();
	}
}
```

Which works as expected:
```
# HELP grpc_requests_received_total Number of received gRPC requests
# TYPE grpc_requests_received_total counter
grpc_requests_received_total{service="greet.Greeter",method="SayHello"} 4
```

Would you accept a PR for this? It has a dependency on `Grpc.AspNetCore.Server` though, so I guess it'd have to be a separate assembly like `Prometheus.Grpc` or something similar.

**Comment by JosephWoodward** [comment]
> so I guess it'd have to be a separate assembly like Prometheus.Grpc or something similar.

Agreed, sounds like something that should live in a separate assembly.
