### ISSUE TITLE
Prometheus-net can't reach metrics on kubernetes

### ISSUE THREAD

**Issue by ER-git** [prometheus-net/prometheus-net#214]
Hey I wrote .net core application (core 3 not ASP.net).
And im using the following:
```
            MetricServer server = new MetricServer(hostname: "localhost", port: MetricsPort);
            server.Start();
```
Also tried 127.0.0.1 instead of localhost.
on windows everything is running great , but when I try to reach the address on kubernetes(using node-port) I receive XXX.XXX.X.XX refused to connect.
Docker file got expose param as follow:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
WORKDIR /app

EXPOSE 9090
EXPOSE 30000
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic AS build
WORKDIR /src

COPY XXXXX
COPY XXXX
COPY XXXXX
RUN dotnet restore XXXX
COPY . .
WORKDIR /src/XXX
RUN dotnet build XXXX -c Release -o /app

FROM build AS publish
RUN dotnet publish XXXX -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
EXPOSE 9090
EXPOSE 30000
EXPOSE 8080
ENTRYPOINT ["dotnet", "XXX.dll"]
```
And the target port where the MetricsPort is on 9090

**Comment by sandersaares** [comment]
This sounds like a question of container network communications design and configuration and therefore out of scope for an issue in the repository of the prometheus-net library. As such, I close this issue.

**Comment by ChristopherLenz** [comment]
@ER-git were you able to solve it. I have a similar problem, which is really strange. I have roughly 10 .net Core APIs running. Everyone can be reached in Kubernetes. Except this one which only purpose is to expose some metrics.
