### ISSUE TITLE
AspNet NetFramework implementation hangs

### ISSUE THREAD

**Issue by lukethompsxn** [prometheus-net/prometheus-net#215]
So I have configured the route in my `Global.asax` using `   AspNetMetricServer.RegisterRoutes(GlobalConfiguration.Configuration)` as defined in the docs. I have added a counter to an endpoint, incrementing the counter on each successful processing at the endpoint, as per the docs. However, all requests to the `/metrics` on this host just hang and never gets a response. This happens both when configured inside prometheus as a scrape target and when accessing the `/metrics` url directly. (I used fiddler to inspect the web requests and I can see they are not getting any response).

If I try access the `/metrics` url, all subsequent requests to other endpoints also hang, and after x requests by prometheus scraper, all subsequent requests to other endpoints also hang.

I took the source code for AspNetMetricServer and modified the content of the response to simply be a StringContent hello and it returns fine, so it seems the issue is within the `CollectAndExportAsTextAsync` method, unless there is some weird config I am missing. 

[update]
After more investigation, it appears that this is an issue with the stream not being flushed. The headers are returned on the first request, but the body is never returned. 

[update 2]
After further investigation it seems the underlying implementation of the `PushStreamContent` class is a `CompleteTaskOnCloseStream` class which does not flush, hence closing of the stream is required. This does not actually close the underlying stream though because you are not the owner, see the implementation [here](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/PushStreamContent.cs). Hence in method `FlushAsync` in file `TextSerializer.cs`, after calling `FlushAsync` on the stream, you need to call `_stream.Value.Close();` which completes the task, hence returning the body of the request.

**Comment by steven-dawkins** [comment]
Hi Luke, 

I just started trying to get prometheus running on .net framework project and ran straight into this problem.

Thanks for the detailed issue and investigation, that enabled me to unblock myself pretty quickly.

I think the stream needs to be closed in the AspNetMetricServer class as it's the PushStreamContent that expects close to be called on the stream it supplies. The downstream code could be shared by code following different conventions.

see my PR here: https://github.com/prometheus-net/prometheus-net/pull/216

**Comment by sandersaares** [comment]
Thanks for reporting, analyzing and publishing a fix!

**Comment by sandersaares** [comment]
The fix is now available in preview NuGet package version 3.6.0-pre-000129-bd91778. Please give it a try. If no problems are reported within a few days, I will publish this build as stable package.
