### ISSUE TITLE
AspNetMetricServer does not use the registry

### ISSUE THREAD

**Issue by lukethompsxn** [prometheus-net/prometheus-net#217]
As part of the handler implementation, it takes the registry which the user wishes to use, however instead of using this registry in `SendAsync` it always uses the default `Metrics.DefaultRegistry` where it should use `_registry` to allow for custom registries to be used.

**Comment by sandersaares** [comment]
The fix is now available in preview NuGet package version 3.6.0-pre-000129-bd91778. Please give it a try. If no problems are reported within a few days, I will publish this build as stable package.
