### ISSUE TITLE
prometheus-net.NetFramework.AspNet bug

### ISSUE THREAD

**Issue by chenqi723** [prometheus-net/prometheus-net#219]
use prometheus-net.NetFramework.AspNet

visit http://localhost:16057/metrics

the request is Loading all the time

**Comment by lqkankan** [comment]
Hi, 
please search 'RegisterRoutes' in this repository and rewrite the extension class with below code in your project

    public static class CustomMetricServer
    {
        public sealed class Settings
        {
            public CollectorRegistry Registry { get; set; }
        }

        /// <summary>
        /// Registers an anonymous instance of the controller to be published on the /metrics URL.
        /// </summary>
        public static void RegisterRoutes(HttpConfiguration configuration, Settings settings = null)
        {
            if (configuration == null)
                throw new ArgumentNullException(nameof(configuration));

            configuration.Routes.MapHttpRoute(
                name: "Prometheus_Default",
                routeTemplate: "metrics",
                defaults: null,
                constraints: null,
                handler: new Handler(settings?.Registry ?? Metrics.DefaultRegistry));
        }

        private sealed class Handler : DelegatingHandler
        {
            public Handler(CollectorRegistry registry)
            {
                _registry = registry;
            }

            private readonly CollectorRegistry _registry;

            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                // The ASP.NET PushStreamContent does not have a way to easily handle exceptions that
                // occur before we write to the stream (when we can still return nice error headers).
                // Maybe in a future version this could be improved, as right now exception == aborted connection.

                var ms = new MemoryStream();
                Task.WaitAll(Metrics.DefaultRegistry.CollectAndExportAsTextAsync(ms, cancellationToken));
                byte[] bs = ms.ToArray();
                var s = System.Text.Encoding.UTF8.GetString(bs);

                var resp = new HttpResponseMessage(HttpStatusCode.OK);
                resp.Content = new StringContent(s, System.Text.Encoding.UTF8, "text/plain");
                return Task.FromResult(resp);
                //return Task.FromResult(request.CreateResponse(HttpStatusCode.OK, s, new MediaTypeHeaderValue(@"text/plain")));
            }
        }
    }


then use 
CustomMetricServer.RegisterRoutes(GlobalConfiguration.Configuration);
to replace
AspNetMetricServer.RegisterRoutes(GlobalConfiguration.Configuration);

it works for me.

**Comment by lqkankan** [comment]
> use prometheus-net.NetFramework.AspNet
> 
> visit http://localhost:16057/metrics
> 
> the request is Loading all the time

**Comment by lqkankan** [comment]
@chenqi723

**Comment by sandersaares** [comment]
I think this is same as #215. Fixed version to be published this week.

**Comment by sandersaares** [comment]
The fix is now available in preview NuGet package version 3.6.0-pre-000129-bd91778. Please give it a try. If no problems are reported within a few days, I will publish this build as stable package.

**Comment by sandersaares** [comment]
3.6.0 with the fix is now published.
