### ISSUE TITLE
TaskCanceledException thrown when calling MetricsPusher.Stop()

### ISSUE THREAD

**Issue by Cronan** [prometheus-net/prometheus-net#221]
I'm running the MetricPusher from a .NET Framework 4.6.2 Console Application
Running on Windows 10 64-bit (1809)

## Exception
```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

  This exception was originally thrown at this call stack:
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
```
## Call Stack
![image](https://user-images.githubusercontent.com/777435/84242073-3a99f100-aaf8-11ea-9f93-e6d7a86d3c51.png)

**Comment by Cronan** [comment]
If I don't stop it I keep on getting metrics not published (on some runs)

**Comment by Cronan** [comment]
Same behaviour calling `StopAsync().Wait()`

**Comment by sandersaares** [comment]
There is a try-catch around the exact place where this happens, which is supposed to eat this exception.

Are you perhaps running with some special exception configuration? "Break on throw"? I can only suspect a debugging configuration issue here.

**Comment by Cronan** [comment]
You're 100% correct, it's only doing this with a debugger attached and it was my debug config.
Thank you for a great piece of software btw.
