### ISSUE TITLE
netcoreapp3.1 target for Prometheus.AspNetCore

### ISSUE THREAD

**Issue by semyon2105** [prometheus-net/prometheus-net#222]
Looks like `Prometheus.AspNetCore` is missing the `netcoreapp3.1` target. This causes the `Microsoft.AspNetCore 2.2` package set to be pulled from NuGet when `Prometheus.AspNetCore` is restored in a `netcoreapp3.1` project.

The desired behaviour would be to use a framework reference to `Microsoft.AspNetCore.App` for the `netcoreapp3.1` target like it's already set up for the `netcoreapp3.0` target.

**Comment by semyon2105** [comment]
This PR fixes it: https://github.com/prometheus-net/prometheus-net/pull/223

**Comment by sandersaares** [comment]
Thanks! What exactly is the logic that applies here? I would have assumed 3.1 falls back to 3.0, not to netstandard. Will this require a new change for every .NET Core version? What's the long term solution?

**Comment by semyon2105** [comment]
It was a mistake on my part. `netcoreapp3.1` target falls back correctly to `netcoreapp3.0` after all. `prometheus-net.AspNetCore` with `netstandard2.0` target was being resolved because I had `netstandard2.0` and `netcoreapp3.1` projects mixed up.

Sorry for bothering you :)
