### ISSUE TITLE
Include RoutePattern and Path in http_request_* metrics

### ISSUE THREAD

**Issue by tpodolak** [prometheus-net/prometheus-net#225]
Current implementation of HTTP like metrics for ASP.NET Core dump labels for code,method,controller and action.
```text
http_request_duration_seconds_sum{code="401",method="GET",controller="Weather",action="Get"} 0.1214422
http_request_duration_seconds_count{code="401",method="GET",controller="Weather",action="Get"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.001"} 8
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.002"} 16
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.004"} 18
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.008"} 20
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.016"} 20
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.032"} 20
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.064"} 20
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.128"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.256"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="0.512"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="1.024"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="2.048"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="4.096"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="8.192"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="16.384"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="32.768"} 21
http_request_duration_seconds_bucket{code="401",method="GET",controller="Weather",action="Get",le="+Inf"} 21
```

Would it be possible to also add request path and route template to the labels?
Route path could be extracted from `HttpContext.Request.Path` property, whereas RoutePattern could be extracted from `HttpContext.GetEndpoing()` method
```c#
(context.GetEndpoint() as RouteEndpoint)?.RoutePattern.RawText
```
With current set of labels, it is difficult to query prometheus in case you have same naming for the controllers in different namespaces eg
```c#
[Route("v1/weather")]
public class WeatherController : ControllerBase
{
}

[Route("v2/weather")]
public class WeatherController : ControllerBase
{
}
```
Assuming you are OK with the propsed chagnes, I can take care of the implementation(with some help from your side regarding naming etc)

**Comment by sandersaares** [comment]
I can see the value in the route pattern being included. Sure, please send a PR and let's dicuss details in the PR comments.

Including the path itself in labels seems a bit less desirable - keeping the set of label values low is an important goal to keeping metrics structure sane. For some apps, the set of paths might be small but for others it might quickly explode. Do you have a specific scenario in mind where including the actual request path would be important? Perhaps we can come up with an alternative solution in such case.

**Comment by tpodolak** [comment]
>I can see the value in the route pattern being included. Sure, please send a PR and let's dicuss details in the PR comments.

Great, I will try to take care of that within next two weeks.

>Including the path itself in labels seems a bit less desirable - keeping the set of label values low is an important goal to keeping metrics structure sane. For some apps, the set of paths might be small but for others it might quickly explode. Do you have a specific scenario in mind where including the actual request path would be important? Perhaps we can come up with an alternative solution in such case.

We are aiming to use https://github.com/microsoft/aspnet-api-versioning/ for versioning of our API. This means that we no loger will be using "hardcoded" versions in the route path, but we will use the library capabilities to achieve that. This means that routes patterns/templates will be changed from e.g `[Route("v1/weather")]` to `[Route("v{version:apiVersion}/weather")]`. As the route templates will be the same for v1 and v2 versions, it will be impossible to write a query to prometheus to get e.g req/s per versioned endpoint. With path in the labels I was hoping to extract the version from the route and incorporate that in prometheus query. Of course I am open for other solutions, in fact all I need is one additional value from RouteValueDictionary - as the value of  `version:apiVersion` will be there.

**Comment by sandersaares** [comment]
> Of course I am open for other solutions, in fact all I need is one additional value from RouteValueDictionary as separate/custom - as the value of version:apiVersion will be there.

I think this might be the best way forward - to extend the HTTP metrics to allow custom route parameters to be included in labels. I have an idea on how to do this - will try implement it. If this feature satisfies your need, we can probably ignore the route pattern.

**Comment by sandersaares** [comment]
Okay, I have published version 4.0.0-pre-000134-2fea549 in which you can do this:

```csharp
app.UseHttpMetrics(options =>
{
    options.AddRouteParameter("foo");
    options.AddRouteParameter("bar");
});
```

Please let me know if this satisfies your use case.

**Comment by tpodolak** [comment]
> Okay, I have published version 4.0.0-pre-000134-2fea549 in which you can do this:
> 
> ```cs
> app.UseHttpMetrics(options =>
> {
>     options.AddRouteParameter("foo");
>     options.AddRouteParameter("bar");
> });
> ```
> 
> Please let me know if this satisfies your use case.

Thanks, that works perfectly and solves the issue with the missing API version in the metrics. I've also opened PR for adding a route template/pattern to the metrics, please take a look at [it](https://github.com/prometheus-net/prometheus-net/pull/228) when you have time

**Comment by sandersaares** [comment]
To clarify - is your use case fully satisfied by adding a route parameter? If so, I will keep the route parameter feature out of the library for the time being, just to keep the feature set simple and focused.

**Comment by alfhv** [comment]
Is there a way to extend this implementation to allow to add arbitrary data to http_request_* metrics ??
in my case, I need to add cluster information to filter metrics by machine groups.

**Comment by sandersaares** [comment]
> in my case, I need to add cluster information to filter metrics by machine groups.

The standard place where static labels should be added is in the Prometheus server configuration (whatever logic discovers your Prometheus endpoints should also provide all the static information about them).

Does your use case prevent that approach from being used?

**Comment by sandersaares** [comment]
@alfhv Static labels are now available in prerelease build `4.1.0-pre-000171-15be8f3`: https://github.com/prometheus-net/prometheus-net#static-labels

Please give it a try and let me know if it satisfies your needs in this scenario.

**Comment by alfhv** [comment]
Sure, I'll try and let you know

Le dim. 6 déc. 2020 à 18:35, Sander Saares <notifications@github.com> a
écrit :

**Comment by alfhv** [comment]
sorry for late feedback. all good for me.

**Comment by tomasfreund** [comment]
Hi, I'd definitely appreciate an option to use the route pattern instead of controller+action because controller and action are MVC concepts and the exporter should work with ASP.NET Core in general (e.g. when using endpoint routing).

**Comment by pecigonzalo** [comment]
Is this now active? I believe it is, but this issue is still open.

Im trying to use this in F# but I cant seem to make it work:
```
let pathParam =
        HttpMetrics.HttpRouteParameterMapping("Path", "path")

    app.UseMetricServer() |> ignore

    app.UseHttpMetrics(fun options -> options.AddRouteParameter(pathParam))
    |> ignore
```

I could not pass `"Path"` directly, it would not take it as it expects a `HttpRouteParameterMapping`.

**Comment by pecigonzalo** [comment]
I see why this might still be open now, while we can extract route parameters, these do not work with `Request.Path` and `ctx.GetEndpoint()` which are required in some applications (like the example I was talking about before).

**Comment by csseba** [comment]
> > Okay, I have published version 4.0.0-pre-000134-2fea549 in which you can do this:
> > ```cs
> > app.UseHttpMetrics(options =>
> > {
> >     options.AddRouteParameter("foo");
> >     options.AddRouteParameter("bar");
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know if this satisfies your use case.
> 
> Thanks, that works perfectly and solves the issue with the missing API version in the metrics. I've also opened PR for adding a route template/pattern to the labels, please take a look at [it](https://github.com/prometheus-net/prometheus-net/pull/228) when you have time

Hi @sandersaares @tpodolak ,

I am using this lib version and in the startup.cs I have following code:

app.UseHttpMetrics(options => { options.AddRouteParameter("route"); });

However, when I get metrics, I'm getting route = ""
http_request_duration_seconds_bucket{code="404",method="GET",controller="TestController",action="Get",route="",le="0.016"} 0

What should I do in order to have the route value correctly mapped?

I am using .net core 3.1 and my controllers classes are like:
[Route("v2.0/products-test")]

I think I misunderstand something.

Thanks in advance

**Comment by sandersaares** [comment]
`options.AddCustomLabel()` can now be used to add custom labels, including path.

**Comment by FrankRua** [comment]
@sandersaares Just found this issue and I'm curious if it's the same thing we're facing. We are using `prometheus-net` for our endpoints that are versioned like `[Route("v{version:apiVersion}/weather")]` (so not hard coded but using the Microsoft package to do so).

On Prometheus when the metrics are published though it will literally render as `v{version:apiVersion}/weather` and not like `v1/weather` and `v2/weather`. Do you have any idea how we could fix this?

CC: @tpodolak since you were the person that opened the issue.

Thank you!

**Comment by david-shanks** [comment]
> @sandersaares Just found this issue and I'm curious if it's the same thing we're facing. We are using `prometheus-net` for our endpoints that are versioned like `[Route("v{version:apiVersion}/weather")]` (so not hard coded but using the Microsoft package to do so).
> 
> On Prometheus when the metrics are published though it will literally render as `v{version:apiVersion}/weather` and not like `v1/weather` and `v2/weather`. Do you have any idea how we could fix this?
> 
> CC: @tpodolak since you were the person that opened the issue.
> 
> Thank you!

+1

Having the same problem. My applications are versioned the same way and not resolving this value when prometheus-net is registered.
