### ISSUE TITLE
Asp.net core metrics reset period

### ISSUE THREAD

**Issue by muradgaribzada** [prometheus-net/prometheus-net#226]
As far as i understand prometheus-net keeps metrics in memory. So how often it resets? Or how to configure periodically clear old metrics data from memory

**Comment by sandersaares** [comment]
The ASP.NET Core metrics data is kept in memory forever. No reset happens.

Prometheus-net is quite efficient at resource use and you do not need to worry about cleanup when integrating into a typical ASP.NET Core app.

**Comment by muradgaribzada** [comment]
I am using only Histogram metric type and created 
public class ResponseTimeMiddleware
    {
        private readonly RequestDelegate _next;

        public ResponseTimeMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(HttpContext context)
        {
            var sw = Stopwatch.StartNew();
            await _next(context);
            sw.Stop();
            var histogram =
                Metrics
                    .CreateHistogram(
                        "apms_response_time_seconds",
                        "APMS Response Time in seconds",
                        new HistogramConfiguration()
                        {
                            Buckets = Histogram.ExponentialBuckets(0.01, 2, 16),
                            LabelNames = new string[] { "method", "path" }
                        }
                        );

            histogram.WithLabels(context.Request.Method, context.Request.Path)
                     .Observe(sw.Elapsed.TotalSeconds);
        }
 for that.  In a short time my **/metrics**  data became bigger (I'm logging each request metric).   How to be sure whether it will not use more memory after a period of time?

**Comment by sandersaares** [comment]
To avoid excessive memory use, ensure that you do not create excessively diverse label value sets. It is important to ensure that different HTTP requests have the same values given in `.WithLabels()` (to maximum extent possible).

The path, in particular, is a bad choice for a label - there can be many many different paths (e.g. what if a bad actor starts spamming different paths just to crash your web server). You should instead use something more constrained, such as the controller/action labels used in the built-in ASP.NET Core HTTP metrics.

If you are certain you wish to use the path as a label, you can remove old values using `.RemoveLabelled()`. You will need to implement the tracking yourself, of course. Maybe something like only publishing the last 1000 label sets? But this is really just applying a workaround for a bad label set decision in the first place. Don't use path as a label - don't use anything user-controlled with an unbounded set of values.

**Comment by muradgaribzada** [comment]
Thanks for clear explanation. I've changed my approach and started to use asp.net core HttpMetrics middleware.
