### ISSUE TITLE
Upgrading from Prometheus 2 (2.1.3) to Prometheus 3

### ISSUE THREAD

**Issue by SBFrancies** [prometheus-net/prometheus-net#227]
Hi, we're trying to upgrade from version 2.1.3 to version 3.6.0 and are coming across some breaking changes - for example the Prometheus.Advanced.DataContracts namespace doesn't appear to exist anymore. I was wondering if there is an upgrade guide anywhere?

**Comment by sandersaares** [comment]
I do not believe there is anything like an upgrade guide anywhere in the documentation. However, feel free to post questions about specific issues you encounter during the migration.

The `Prometheus.Advanced.DataContracts` namespace used to contain protocol buffer data structure definitions used by prometheus-net. The protocol buffers output format is no longer supported by this library, as this format is deprecated. You should remove any dependency you have on this namespace or the objects within. If you describe the scenario where this namespace is used, I may be able to provide more comments.

**Comment by sandersaares** [comment]
I am closing this due to no response for a long time. Feel free to open a new issue if you continue to need help with this.
