### ISSUE TITLE
MetricServer with Https

### ISSUE THREAD

**Issue by amatabuena** [prometheus-net/prometheus-net#237]
Hi, 

I am trying to use MetricServer with https enabled (useHttps: true) but it doesn't work. When enabled I can't connect to server due to security problems. I have installed versino 3.5.0 of Nuget Package

The MetricServer constructor doesn't allow passing certificate as parameter and I couldn't find another way to set up a certificate.

How can I set up a certificate?

Thanks

**Comment by sandersaares** [comment]
The certificate needs to be configured on the operating system level, using `netsh` command. See here: https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-configure-a-port-with-an-ssl-certificate
