### ISSUE TITLE
Question: Adding additional labels to default metrics

### ISSUE THREAD

**Issue by JosephWoodward** [prometheus-net/prometheus-net#238]
I'd like to add an additional custom label beyond HTTP route parameters (say, an instance ID for example) to the existing default `http_requests_received_total ` metric, can this be done? If not, what's the correct approach? Creating a new metric and hide the `http_requests_received_total` via `o.RequestDuration.Enabled = false;`?

**Comment by sandersaares** [comment]
Please clarify - where would the value for this extra label come from?

**Comment by JosephWoodward** [comment]
> Please clarify - where would the value for this extra label come from?

Read into the application's configuration via an environment variable on the EC2 instance for example.

**Comment by sandersaares** [comment]
Understood. Would the design described in #256 satisfy this use case?

**Comment by sandersaares** [comment]
Static labels are now available in prerelease build `4.1.0-pre-000171-15be8f3`: https://github.com/prometheus-net/prometheus-net#static-labels

Please give it a try and let me know if it satisfies your needs in this scenario.

**Comment by sandersaares** [comment]
There is also `options.AddCustomLabel()` available in 6.0.0 preview which might help cover any gaps here.
