### ISSUE TITLE
Capability to parse generated Prometheus metrics

### ISSUE THREAD

**Issue by tomkerkhove** [prometheus-net/prometheus-net#239]
Does the client provide the capability to pull & parse generated metrics on an endpoint?

If not, do you recommend any other frameworks?

Use case would be to write integration tests to pull the generated metrics and ensure they are written correctly.

**Comment by sandersaares** [comment]
There is no such functionality in prometheus-net.

I have not explored whether a convenient library exists for this. However, the Prometheus export data format is quite simple so it might not be too difficult to make a parser for it if you cannot find an existing one.

**Comment by tomkerkhove** [comment]
Thanks for letting me know!

**Comment by tomkerkhove** [comment]
Maybe just a small question, are you planning on adding it or not per se?

Just to know if I should keep it open or not.

**Comment by sandersaares** [comment]
There are no plans to add this feature - this library is strictly for instrumenting apps to export metrics.

**Comment by tomkerkhove** [comment]
Makes sense, thanks for the feedback!
