### ISSUE TITLE
How to ignore counting requests to /metrics endpoint?

### ISSUE THREAD

**Issue by runerys** [prometheus-net/prometheus-net#243]
Http Requests to paths not handled by controllers are labelled with controller="" and action="". This includes the metrics endpoint, health checks and similar responses served by middleware. Is this by design?

http_requests_received_total{code="200",method="GET",controller="WeatherForecast",action="Get"} 1 <-- Regular controller
http_requests_received_total{code="200",method="GET",controller="",action=""} 4 <---- Health checks and /metrics etc.

Is there a way for me to configure Http metrics to ignore certain routes/paths? (I've looked quite hard)

Maybe this is by design since these metrics could be interesting to query at some time in the future. But then I wouldn't be able to differ health checks from the /metrics scraping endpoint (since both have the same blank labels).

Or maybe this should be handled/filtered away by the Prometheus server later? Advice appreciated :)

**Comment by JosephWoodward** [comment]
Hi @runerys,

I believe this is by design. Anything without a controller/action will fall into the empty labels. A PR was recently [raised here](https://github.com/prometheus-net/prometheus-net/pull/228) that adds route data as a label which might be more helpful to you, however this also requires the middleware to use the new EndpointRouting in some instances, but it's certainly better.

**Comment by sandersaares** [comment]
> Http Requests to paths not handled by controllers are labelled with controller="" and action="". This includes the metrics endpoint, health checks and similar responses served by middleware. Is this by design?

Yes.

> Is there a way for me to configure Http metrics to ignore certain routes/paths? (I've looked quite hard)

Yes. At its core, all ASP.NET Core middleware can be selectively triggered based on parameters of the HTTP request. Simple path filtering can be applied as follows:

```csharp
app.UseWhen(context => !context.Request.Path.StartsWithSegments("/metrics"), config =>
{
    config.UseHttpMetrics();
});
```

> Maybe this is by design since these metrics could be interesting to query at some time in the future. But then I wouldn't be able to differ health checks from the /metrics scraping endpoint (since both have the same blank labels).

Making this data more useful would be desirable. However, it is easy to come up with problematic designs here - the HTTP request path can be a wild and variable label in some application scenarios, leading to label bloat and very poor query performance when interacting with the Prometheus database. Accordingly, I do not want to just add the request path as a label. The current approach has been to allow explicit opt-in for cases where more information is desired in the labels (e.g. the ability to record custom route parameters in addition to controller/action).

Does the filtering mechanism I described satisfy your use case?

**Comment by runerys** [comment]
Thank you! I was not aware of the app.UseWhen(...)
It solves my use case 👍
