### ISSUE TITLE
How to delete a set of metrics once scraped?

### ISSUE THREAD

**Issue by DmitrySenin** [prometheus-net/prometheus-net#245]
I have two types of metrics in my app:

1. Live ones which this library aims at
2. Calculated periodically based on a cron

The latter ones can be calculated on different instances of my app. Which would mean that two or more instances could have the same set of metrics but only one of them has the actual values - calculated the very last time.
I'm looking for a way to deliver these metrics to Prometheus. Currently I consider two ways of achieve this:
1. Leverage the push approach
2. Delete these metrics once they get scraped

So far, I'm inclined towards (2) and looking for a hook in the library to be able to remove a set of metrics after they are scraped.

P.S.
I fully understand that this is not a use-case of this library but still would like to hear some possible solutions.

**Comment by sandersaares** [comment]
There is an `.Unpublish()` method available on every metric instance - calling this will suppress this particular metric from the output until the next time the value is updated. Perhaps this satisfies your use case?
