### ISSUE TITLE
WithLabels clarification

### ISSUE THREAD

**Issue by illegalnumbers** [prometheus-net/prometheus-net#249]
Are labels for metrics only picked up by ordinal position in the array for the metric? Would it be possible to submit a hashmap of labels to values at all instead?

**Comment by sandersaares** [comment]
Your understanding is correct - they are only picked up by position.

This is essentially a performance-oriented constraint, to avoid doing extra lookups when processing .WithLabels() - as this may conceivably be called on every metric-update call in some scenarios.

If you are facing a situation where you find it impossible to supply the values by position, please explain your scenario further and I will try offer some advice on how to achieve a solution.
