### ISSUE TITLE
Add default metrics to custom registry

### ISSUE THREAD

**Issue by arshrp** [prometheus-net/prometheus-net#250]
I am creating custom Prometheus registries via Metrics.NewCustomRegistry() and I have attached that registry to the default /metrics endpoint via IEndpointRouteBuilder.MapMetrics().  So now I can see my custom metrics displayed at the /metrics endpoint, which is great.

But now that I'm using a custom registry, all the default Prometheus metrics as well as the metrics added by UseHttpMetrics() middleware are no longer displaying.

Is there a way to add default metrics to a custom registry?  I would like to avoid using two separate endpoints for this if possible.

**Comment by sandersaares** [comment]
You can register the default metrics using `DotNetStats.Register(registry)`.
