### ISSUE TITLE
Basic Authentication for Standalone HTTP Handler

### ISSUE THREAD

**Issue by ethanshea-ms** [prometheus-net/prometheus-net#261]
From #92 I see it is possible to use Basic Auth for the ASP.NET HTTP Handler. Is this also possible for the standalone HTTP Handler?

Example:

```csharp
var metricServer = new MetricServer(port: 1234);
// How do I apply basic authentication here?
metricServer.Start();
```

**Comment by sandersaares** [comment]
This is not currently supported, though could likely be added.

The first design that comes to mind is a request filtering callback such as:

```csharp
metricServer.RequestFilter = request => IsAuthorized(request.Headers.Authorization);
```

Would this satisfy your use case? What is the authorization logic you would like to apply? That is, where do the credentials come from and how would they be validated?

I would also be interested to hear more about your usage of MetricServer. It is the oldest mechanism for publishing metrics in the library and over the years is moving ever more into the "legacy" category, so it would be good to better understand the needs of people who still want to use it, to keep it getting the attention it needs. What makes you prefer this mechanism over the others available?

**Comment by ethanshea-ms** [comment]
Yes, that sort of a design would work. The design you proposed is reminiscent of [`SslOptions.RemoteCertificateValidationCallback`](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.remotecertificatevalidationcallback?view=netcore-3.1). 

My use case involves shipping code to be run in [Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/module-development). [Direct method calls](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-edgeagent-direct-method) are used for interacting with IoT Edge modules, so there is no need for ASP.NET/Kestrel. We are trying to avoid taking a dependency on it if possible.
