### ISSUE TITLE
Any plan for diagnostic source support?

### ISSUE THREAD

**Issue by WeihanLi** [prometheus-net/prometheus-net#262]
With diagnostic source, we could do some metrics with less code and the code will be more clean, mostly APM libraries like elastic apm, skywalking just do it this way, so I'm wondering if there's any plan for diagnostic source support

**Comment by sandersaares** [comment]
Hi! What specifically is the feature set of interest to you? Basic support is already available: https://github.com/prometheus-net/prometheus-net#diagnosticsource-integration

**Comment by WeihanLi** [comment]
Sorry I missed that, I noticed that `HttpClient` metrics was introduced recently with `DelegatingHandler`, I' wondering that if we use the diagnostic source, the code maybe will be more clean
