### ISSUE TITLE
standalone HTTP handler - Metrics endpoint unavailable after periods of inactivity

### ISSUE THREAD

**Issue by amfrye777** [prometheus-net/prometheus-net#263]
We have used the prometheus-net standalone HTTP handler for a windows .net framework application. Metrics are working fine while there is activity on the application. When activity halts for an extended period, the metricServer appears to spin down until a new updates come through to a metric (aka application is no longer inactive and the metricServer spins back up). 

When the MetricServer spins down, it causes our Alerts for Down Targets to fire(up==0), causing a "faulty" alert... because as soon as new activity occurs in the application the metric server resumes without problem. 

I am unsure if this is related to our configuration of the prometheus-net library, an issue with our `netsh http` options for allowing permissions for the specified port number, or something else. 

I'm unsure what type of additional information to share here - so please let me know and I'll track it down and share.

**Comment by sandersaares** [comment]
There is no such feature in prometheus-net - the MetricServer will serve requests forever. I suspect this may be something specific to your deployment configuration.
