### ISSUE TITLE
HttpClientRequestDurationHandler not recording correct duration

### ISSUE THREAD

**Issue by kenkam** [prometheus-net/prometheus-net#265]
### Steps to reproduce

1. Create an empty dotnet web project
2. Use `HttpClientMetrics()` and `MapMetrics()`
```c#
    services.AddHttpClient<FooApi>()
        .UseHttpClientMetrics();
    ...
    
    app.UseEndpoints(e => e.MapMetrics())
```
3. Exercise the HttpClient, and compare metrics from the console logs vs /metrics

### Expected

* Console log timing should be similar to /metrics

### Actual

* Metrics is much lower than expected

---

`HttpClientRequestDurationHandler` is returning the Task directly without awaiting for the request task to complete. This means the timer is disposed as soon as the method is returned and is actually recording method invocation time, not actual client request duration.

**Comment by AndrewP-GH** [comment]
@sandersaares Hello!
Are you going to merge this fix in the nearest feature? Without it, `UseHttpClientMetrics` isn't very useful.
