### ISSUE TITLE
Unintended PackageReference to Microsoft.AspNetCore when targeting net5.0

### ISSUE THREAD

**Issue by baronfel** [prometheus-net/prometheus-net#267]
The project file logic [here](https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus.AspNetCore/Prometheus.AspNetCore.csproj#L35-L37) results in a PackageReference to the old aspnetcore nuget packages when using this library in a net5.0 application.

I believe it should be as simple as changing the logic here to be the inverse of the condition [here](https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus.AspNetCore/Prometheus.AspNetCore.csproj#L39), which would allow for some flexibility on new runtimes.

Alternatively, the library could be updated to multitarget to net5.0 and do a similar condition for net5.0.

In any case, I'd be happy to contribute this change.

**Comment by sandersaares** [comment]
I am unable to reproduce this - adding a reference to prometheus-net.AspNetCore only references .NET 5 ASP.NET Core packages. Please provide specific steps to reproduce the problem.

**Comment by heggi** [comment]
Same problem

Code for reproduce this

```csharp
public static void Main()
{
    var server = new KestrelMetricServer(port: 12345);
    server.Start();
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <Nullable>Enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="prometheus-net.AspNetCore" Version="4.1.1" />
    </ItemGroup>
</Project>
```

Got
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Не удается
найти указанный файл.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Prometheus.KestrelMetricServer.StartServer(CancellationToken cancel)
   at Prometheus.MetricHandler.Start()
   at XRad2LB.Program.Main() in U:\Project\xrad2lb\XRad2LB\Program.cs:line 18
```

If I use MetricServer (not KestrelMetricServer), compiling successful, but I got `Unhandled exception. System.Net.HttpListenerException (5) Access Denied` on windows 10 (and normal run in docker container)

**Comment by sandersaares** [comment]
Thanks for the repro case! I can reproduce the problem now. However, it only reproduces if I do not follow the readme instructions: https://github.com/prometheus-net/prometheus-net#kestrel-stand-alone-server

Specifically, the readme says to use the Web SDK: `<Project Sdk="Microsoft.NET.Sdk.Web">`. If I modify the csproj to use the web SDK, the error does not reproduce anymore. Can you confirm/deny? If it still reproduces for you, please share a zip of your project so I can examine the differences.

While I do want to simplify installing the library into console apps even when using the default SDK, I am slightly uncomfortable with adding each and every .NET version into the project file configurations, as this reduces the maintainability of the library and causes extra work to get it published. I will explore some options here.

**Comment by sandersaares** [comment]
Aha, I think I found the right way to automatically reference the web SDK! Will publish new version that might help get past this with minimal hassle and without making a net5.0 specific build, which I want to avoid.

**Comment by sandersaares** [comment]
Version 4.2.0 with this fix is uploading now. This should make the install process for .NET 5 console apps easier. It seems to work in my testing - please open a new issue for best visibility if you still experience issues.
