### ISSUE TITLE
Unit testable code

### ISSUE THREAD

**Issue by jbrekle** [prometheus-net/prometheus-net#268]
Hi folks, 
I would be interested in getting to know your opinion about making the library work in unit tests.
Is there something I miss, or is it currently impossible to write unit tests for code that uses the library?
E.g. I have my consuming code 
```
   public class MetricLogger 
   {
        private static Counter _methodCallCounter = Prometheus.Metrics.CreateCounter(
            "ServiceName_call_count",
            "counter of calls", 
            new []{"method"});

        public void OnCalled(string key)
        {
            try
            {
                _methodCounter.Labels(key).Inc();
            }
            catch (Exception exc)
            {
                _logger.LogError(default, exc, "Could not log metric.");
            }
        }
  }
```
And now I want to unit test if the counter has been created and the `Inc` method has been called. There is no way to access the counters in the registry. Everything is hardwired to real implementations. 

The solution here would be quite simple: 

- to give the `CollectorRegistry` an interface `ICollectorRegistry`
- expose the registered `Collector`'s in the new `ICollectorRegistry`
- allow MetricFactory to accept `ICollectorRegistry` instead of `CollectorRegistry`
- to give the `MetricFactory` an interface `IMetricFactory`
- extend `Metrics` with an option to set `_defaultFactory` from outside (eg. `SetMetricFactoryForTests`)

That would even enable me to remove the call to the static `Metrics` class in my consuming code and pass in a mockable `IMetricFactory` as constructor dependency.

If you think that makes sense, I could try to make PR.
Regards,
jbrekle

**Comment by sandersaares** [comment]
It is true that the factories/registries are not exposed via interfaces. On the other hand, there are interfaces for the metric types, such as `IGauge` and friends, which may provide some value here. A useful pattern that I find is to associate each `MyClass` object with a `MyClassMetrics` object where one instance of `MyClassMetrics` provides the metric instances relevant to a specific instance of `MyClass`. This enables testability of the interactions between `MyClass` and its metrics. The real implementation of `MyClassMetrics` can use `Metrics.CreateXYZ()` whereas one used in testing can use suitable substitutes.

Does this satisfy your needs?

**Comment by jbrekle** [comment]
Of course it's possible to wrap every usage of the library in a hand written wrapper. I think it's a unnecessary crude solution with no benefit. But if you choose to do that, fine.

**Comment by sandersaares** [comment]
I am not necessarily opposed to introducing some interfaces here but I am wondering what the balance point here is. There is a difference between the internal and external API used by the library - the same classes provide different functionality to internal and external usage, so it is not as simple as just switching interfaces in between the calls.

The list of ideas you provide is a good starting point. Here is what I am thinking:

* `IMetricFactory` seems straightforward enough and will allow substitution in "creating metric instances" scenarios.
* `ICollectorRegistry` can also be created to enable substitution in "configuration of registry" and "metrics serialization" scenarios.
* This only affects the external API for these classes - you cannot give an `ICollectorRegistry` to a `MetricFactory` - if you use a real implementation of one, it requires a real implementation of the other.

This seems like a sensible balance point. I will try to throw together some code for this.

**Comment by sandersaares** [comment]
I have added `IMetricFactory` and `ICollectorRegistry` to the repo.

One thing I am not quite satisfied with is that I would like to return some interfaces from `IMetricFactory` instead of concrete types. However, this seems not so easy due to legacy design of the object model in that area. If you have some ideas on how to achieve that with minimum hassle, please submit a PR to evolve the design further in that sense.

**Comment by sandersaares** [comment]
This is now available in prerelease build `4.1.0-pre-000171-15be8f3` that is uploading to nuget.org right now. Please let me know your thoughts on what you see there.

**Comment by DanielBryars** [comment]
Hello, I'm just starting to use prometheus-net - looks great. Like the author of this thread, I don't want to take a concrete dependency on the Prometheus.Metrics type so I can unit test my libraries.

IMetricFactory looks promising, but I don't understand how it's supposed to be used - it returns concrete types. However those concrete types which it returns do implement ICounter, IGauge, so it makes things relatively straightforward.

I thought you might be interested in how I'm using your library. And if there's an easier way to achieve what I'm doing (I tried googling but didn't get very far).

For my purposes I've made an IMetricFactory which returns interfaces, and a wrapper which I can use in my application, I can then use Moq.Mock<IMetricFactory> etc for unit test.

`public interface IMetricFactory
        {
            ICounter CreateCounter(string name, string help, CounterConfiguration? configuration = null);
            IGauge CreateGauge(string name, string help, GaugeConfiguration? configuration = null);
            IHistogram CreateHistogram(string name, string help, HistogramConfiguration? configuration = null);
            ISummary CreateSummary(string name, string help, SummaryConfiguration? configuration = null);
        }`

And a concrete here:

`public class ConcreteMetricFactory : IMetricFactory
        {
            public ICounter CreateCounter(string name, string help, CounterConfiguration configuration = null)
                => Metrics.CreateCounter(name, help, configuration);
            
            public IGauge CreateGauge(string name, string help, GaugeConfiguration configuration = null)
                => Metrics.CreateGauge(name, help, configuration);
            
            public IHistogram CreateHistogram(string name, string help, HistogramConfiguration configuration = null)
                => Metrics.CreateHistogram(name, help, configuration);
            
            public ISummary CreateSummary(string name, string help, SummaryConfiguration configuration = null)
                => Metrics.CreateSummary(name, help, configuration);
        }`

I can then use this in my libraries like this:

`public class SomeService
        {
            private readonly ICounter _myCounter;

            public SomeService(IMetricFactory metricFactory)
            {
                _myCounter = metricFactory.CreateCounter("SomeService Counter", "Help here");
            }

            public void SomeMethod()
            {
                _myCounter.Inc();
            }
        }`

In an app I just register the factory:
.AddSingleton<IMetricFactory,ConcreteMetricFactory.()

And in tests my mock
var mockMetricFactory = Mock.Of<IMetricFactory>();
//... set this up
.AddSingleton((_)=>mockMetricFactory ).

Etc

**Comment by DanielBryars** [comment]
Yeah the above isn't going well for me, instead I've just made an IMetricsFactoryFactory, this means that in my libraries I don't take a dependency on how the MetricsFactory is instantiated, but I do take a dependency on the concretes - which is fine:

`public class MetricFactoryFactory : IMetricFactoryFactory
    {
        private readonly CollectorRegistry _registry;
        private MetricFactory _metricFactory;

        public MetricFactoryFactory()
        {
            _registry = new CollectorRegistry();
            DotNetStats.Register(_registry);
            _metricFactory = Metrics.WithCustomRegistry(_registry);
        }

        public MetricFactory Create()
        {
            return _metricFactory;
        }
    }`

MetricFactoryFactory : IMetricFactoryFactory is registered as a singleton in the DI by the process which consumes the library, and in tests you can make a custom registry if you want.

**Comment by janjuza** [comment]
HI, I would like to mock Counter class, nothing above is straightforward. 
I would like to test methods WithLabels() and Inc(), but they are not even in the same interface.
Would it be possible replace result type Counter by some interface which would implement all other interfaces, to allow mock any method from all Counter's interfaces? I think this could be ultimate solution for all mocking problems.
