### ISSUE TITLE
Documentation - stand-alone server does not mention FrameworkReference

### ISSUE THREAD

**Issue by jeroenlandheer** [prometheus-net/prometheus-net#271]
In the documentation it reads:

> Even when you integrate prometheus-net Kestrel server into a stand-alone console app, the project file must be using the ASP.NET Core SDK. In other words, you must have the .Web at the end of the Sdk attribute value in the project file...

This is not needed, you can add a `<FrameworkReference Include="Microsoft.AspNetCore.Web" />` to the project file. See the documentation about it here: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio 

This has the added advantage that it is not being treated as the 'primary' framework in Visual Studio and therefore will not change the project icon, add irrelevant context menu items, and so on.

**Comment by sandersaares** [comment]
While perhaps true, I am going to consider this an advanced scenario executed at a user's own risk. The supported/advertised mechanism is to require a Web SDK based project - the readme is not designed to cover all possible use cases, so focusing on what is sure to work is the main substance presented there.
