### ISSUE TITLE
Documentation inaccuracy regarding requirement for .Web at the end of the Sdk attribute value in the project file

### ISSUE THREAD

**Issue by matthewkrieger** [prometheus-net/prometheus-net#272]
The [Kestrel stand-alone server](https://github.com/prometheus-net/prometheus-net/blob/master/README.md#kestrel-stand-alone-server) section of the readme says:

> Even when you integrate prometheus-net Kestrel server into a stand-alone console app, the project file must be using the ASP.NET Core SDK. In other words, you must have the .Web at the end of the Sdk attribute value in the project file:
> 
> <Project Sdk="Microsoft.NET.Sdk.Web">

This does not appear be the case. I made a bog standard .NET Standard console app, copied and pasted the code from the [Quick Start](https://github.com/prometheus-net/prometheus-net/blob/master/README.md#quick-start) section and the web server ran fine.  From my .csproj file:

`<Project Sdk="Microsoft.NET.Sdk">`

**Comment by sandersaares** [comment]
The quick start code does not use the Kestrel hosted metric server. Or do you mean you replaced the `MetricServer` with `KestrelMetricServer` in the quick start?

Regardless, the requirement to use a Web SDK project is there to avoid problems with app startup/initialization related to assembly loading. It may be that a minimal sample project does not immediately cause issues but nevertheless, using a Web SDK project is the supported/advertised approach. You may, of course, deviate from this at your own risk but at least some time ago doing this did result in assembly load failures in some scenarios.

**Comment by matthewkrieger** [comment]
Understood. I left `MetricServer` as is.
