### ISSUE TITLE
Zero alloc Labels

### ISSUE THREAD

**Issue by avendel** [prometheus-net/prometheus-net#274]
I have made some experiments optimizing the ``Collector::WithLabels`` code, and have found some changes that would reduce memory allocation and improve performance. Would you be interested in a pull request?

The changes are:

* Make ``Labels`` a struct.
* Avoid allocating for lambda in use of ``Any`` in the Labels constructor.
* Avoid allocating for lambda in ``Collector::GetOrAddLabelled`` by only using ``ConcurrentDictionary::GetOrAdd`` if a call to ``TryGet`` returns false, which should only happen the first time a label is used.

Here are the benchmark results from running the ``WithLabels_ManyMetrics_ManySeries`` benchmark.

```
|   Baseline (before)                 | 23,922.65 ns | 461.411 ns | 615.970 ns | 0.3357 |     - |     - |   13600 B |
|   Make Labels struct                | 23,991.09 ns | 118.811 ns |  92.760 ns | 0.2136 |     - |     - |    9600 B |
|   + Any() -> foreach in constructor | 19,441.14 ns | 361.153 ns | 301.579 ns | 0.1526 |     - |     - |    6400 B |
|   + GetOrAdd only if TryGet fails   | 16,954.60 ns | 294.131 ns | 275.130 ns |      - |     - |     - |         - |
```

Making the ``Labels`` class a struct introduces the negative side effect that an improperly instance can be created, since we can't implement an explicit parameterless constructor. Here are the benchmarks result from only doing the other changes:

```
|   WithLabels_ManyMetrics_ManySeries | 17,188.13 ns | 304.360 ns | 446.126 ns | 17,066.55 ns | 0.0916 |     - |     - |    4000 B |
```

**Comment by sandersaares** [comment]
This sounds like a valuable set of changes. Sure, please submit a PR for the whole set!
