### ISSUE TITLE
Is there a way to initialise metrics to 0 on startup ?

### ISSUE THREAD

**Issue by renoojohn** [prometheus-net/prometheus-net#278]
The increase function in promql doesnt consider the first increment which leads to data loss.   Is there any way we can initialize counter value to 0 on startup?

**Comment by sandersaares** [comment]
[According to the readme](https://github.com/prometheus-net/prometheus-net#when-are-metrics-published), a counter with value 0 will be published when any of the following is true:

1. Label values are defined for the counter (using `.WithLabels()`).
2. `Publish()` is called on the counter.
3. The counter is incremented.

I assume in your scenario neither of these 3 are happening. Without knowing more details about your use case, I suspect calling `.Publish()` on startup might be the path forward for you.

**Comment by sandersaares** [comment]
[According to the readme](https://github.com/prometheus-net/prometheus-net#when-are-metrics-published) metrics become published when any of the following happens:

1. `.WithLabels()` is called.
2. The value of the metric is changed from the default.
3. (Only for unlabeled metrics) `Metrics.CreateXYZ()` is called.

Without knowing more detail about your scenario, I suspect your code might be waiting until the 1st change before it calls `.WithLabels()`. The fix here would be to call `.WithLabels()` as soon as you know the labels to give to the counter (even if you don't want to increment it yet). You can make it extra explicit in code by calling `.WithLabels(...).Publish()`.

If this does not solve your problem, please post a sample project that demonstrates the problem.

**Comment by renoojohn** [comment]
I checked this scenario using the Publish() method.  What I am observing is that the publish method writes an entry 0 for the metric as soon as the label values are ready.  When prometheus scrapes the /metrics endpoint the metric value would have changed from 0 to 1 and the 0 value is not set on prometheus which breaks the increase function calculation.

If by chance,  prometheus scrapes the 0 before increment happens on the counter, the increase function works correctly.

**Comment by sandersaares** [comment]
I see what you mean - you are not getting a gap but rather just legitimately starting with the value of 1. In this case, it sounds like the behavior you experience is by design. Prometheus works best with statistical measurements, it is not the best tool for tracking individual events. Many of the query functions will give you odd results if you try to measure with the accuracy of individual events.

[VictoriaMetrics](https://victoriametrics.github.io/MetricsQL.html) is a Prometheus-compatible system that supposedly fixes many querying gotchas like this. Maybe give it a try?

**Comment by renoojohn** [comment]
Sure, will check that and if it fits our requirements, will go for that.  Thanks @sandersaares
