### ISSUE TITLE
Make the HttpRequestMiddlewareBase to public to easier create custom metrics middleware

### ISSUE THREAD

**Issue by Red0000000008** [prometheus-net/prometheus-net#288]
Currently the 'Prometheus.HttpMetrics.HttpRequestMiddlewareBase' class is defined as internal.
If I want to add more middleware follow the same pattern of default 3 middleware, it's impossible to extend from it.
Since the base middleware option class is treat as public which can be extend, could you please consider to change the HttpRequestMiddlewareBase class to public as well?

**Comment by cubed-it** [comment]
I would like to support this request. Version 4 breaks my application. I need a specially customized middleware.
Is there any good reason why the classes need to be internal?

**Comment by sandersaares** [comment]
The classes in the library are not designed to be building blocks for creating additional 3rd party implementations derived from them - they exist only to make the library work. Some of these internal classes used to be accidentally exposed publically, which was fixed some time ago to avoid accidental dependencies on unstable code.

Please feel free to copy/paste any internal code into your own implementations as needed, if you wish to create such functionality along similar lines.
