### ISSUE TITLE
Problem with NullReferenceException in HttpRequestMiddlewareBase`2.CreateChild

### ISSUE THREAD

**Issue by tlassen** [prometheus-net/prometheus-net#290]
I have an asp.net core 2.1 service running with prometheus. The service uses async/await allot but after enabling prometheus with:

            app.UseMetricServer();
            app.UseHttpMetrics();

Wee start seeing these error sometimes:

```
  System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Method()
     at Prometheus.HttpMetrics.HttpRequestMiddlewareBase`2.CreateChild(HttpContext context, RouteValueDictionary routeData)
     at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
     at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
     at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
     at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```
Have done some digging in the code and it seems to bee this part of prometheus that gives the problems for us:

        protected TChild CreateChild(HttpContext context, RouteValueDictionary? routeData)
        {
            var labelValues = new string[_metric.LabelNames.Length];

            for (var i = 0; i < labelValues.Length; i++)
            {
                switch (_metric.LabelNames[i])
                {
                    case HttpRequestLabelNames.Method:
                        labelValues[i] = context.Request.Method;
                        break;

As far as i am able to see the problem is that HttpContext is not thread safe and there by when wee get to the line context.Request.Method the situation that context.Request is not available any longer might occur. 

This is a service with alot of trafic wich is probberly why i see this problem.

In aps.net core 2.1 the non Threadsafty of HttpContext hase beeden mee bofore :)

**Comment by sandersaares** [comment]
From the description it sounds like something in your app is breaking the HttpContext by removing the IHttpRequestFeature or doing a similar destructive act to break processing of the HttpContext (e.g. calling HttpContext.Uninitialuze()). This would be an error in your app - it is not legal to just break an HttpContext in the middle of an executing pipeline like that.

As far as I can tell, everything is correct here from a prometheus-net behavior viewpoint. If you can provide a sample project that reproduces the issue, I can investigate further.
