### ISSUE TITLE
Order of Labels matter?!

### ISSUE THREAD

**Issue by rparvizian-rbx** [prometheus-net/prometheus-net#292]
I was looking at the implementation of Labels:
https://github.com/prometheus-net/prometheus-net/blob/4dc0b83b280395bc114c5530fa9843a244804f9b/Prometheus.NetStandard/Labels.cs#L92
and I noticed that the order of the names matter, which doesn't make sense, since this would result in two different counters, even though they are equivalent.

**Comment by sandersaares** [comment]
Yes, the order of labels matters. The order is used to match label names with label values, for example.
