### ISSUE TITLE
MetricsPusher can randomly terminate

### ISSUE THREAD

**Issue by einarmo** [prometheus-net/prometheus-net#293]
We have seen this on some long-running applications. We start the metrics, but at some random point they die.

I looked at the code and found something I think may be a potential issue, that I've seen before in a different project:

In [MetricsPusher](https://github.com/prometheus-net/prometheus-net/blob/1cfbebb79719b9016284b7ded8dc5ef93e500fea/Prometheus.NetStandard/MetricPusher.cs) you use OperationCanceledException to check for cancelation due to cancelation token, however if the HTTPClient is configured with a timeout (it is in our case), then it can generate an OperationCanceledException without the CancelationToken being triggered, see [the official docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.postasync?view=net-5.0).

This would cause the loop to terminate silently, which would be a bug.

The solution is simply to check if the cancelation token is triggered, instead of relying on OperationCanceledException, which is a far safer and more correct way to do this to begin with. Even if my explanation is not correct, that should still be changed, since the loop should _never_ be allowed to terminate without an external cancelation.

**Comment by jaimemorais** [comment]
`
        private static void StartPusher(string pushGatewayUrl, string myJob)
        {
            MetricPusherOptions options = new MetricPusherOptions()
            {
                Endpoint = pushGatewayUrl,
                Job = myJob,
                IntervalMilliseconds = 10000,
                HttpClientProvider = GetHttpClient,
                OnError = OnPushError
            };

            MetricPusher = new MetricPusher(options);

            MetricPusher.Start();
        }


        
        private static HttpClient MyHttpClient = new HttpClient();
        private static bool ResetHttpClient = false;
        private static HttpClient GetHttpClient()
        {
            if (ResetHttpClient)
            {
                MyHttpClient.Dispose();
                MyHttpClient = new HttpClient();
                ResetHttpClient = false;
            }
             
            return MyHttpClient;            
        }
                
        private static void OnPushError(Exception ex) 
        {            
            ResetHttpClient = true;
        }`
