### ISSUE TITLE
Usage of custom IGauge implementation

### ISSUE THREAD

**Issue by davidreis97** [prometheus-net/prometheus-net#310]
Hi there!

I'd like to have a gauge that is set to 1 when the connection to a service is up and 0 when the connection is down. The way I achieved this using my previous metrics implementation was to have a property which looked something like the following:

`public double ConnectionStatus => connection?.IsConnected() ?? false ? 1 : 0;`

I realise I can do something similar with JIT updates using `Metrics.DefaultRegistry.AddBeforeCollectCallback()`, but I'd really prefer to implement my own `IGauge` where I can override it's backing property `IGauge.Value` to be whatever I want. 

Given that:
- `MetricsFactory` is hardcoded to use the implementations provided by this library
- `IMetricsFactory` is not an interface that one can implement and use with the rest of the library
- `CollectorRegistry.GetOrAdd` is an internal method

Is it possible to have a custom IGauge implementation?

**Comment by sandersaares** [comment]
The library does not allow custom implementations. The typical pattern in this case would be to create a Gauge instance using `Metrics.CreateGauge()` and to then update the value of this gauge to 0/1 whenever the state of the connection changes.
