### ISSUE TITLE
prometheus-net.AspNetCore 4.3.0 (prerelease) binary incompatibility

### ISSUE THREAD

**Issue by gr-liam** [prometheus-net/prometheus-net#316]
Hi,

The prerelease 4.3.0 versions of prometheus-net.AspNetCore contain binary incompatibilities as the public HttpClientMetricsExtensions type has been removed in https://github.com/prometheus-net/prometheus-net/commit/79466f78886ad8bba6078b5006b2f33287241d7f

Consider the following scenario:
* PackageA references 4.3.0 and PackageB
* PackageB references 4.2.0 and uses HttpClientMetricsExtensions

This will result in a runtime TypeLoadException

It would be great to fix this before 4.3.0 is released, either by adding the type back in (probably just calling into the type in prometheus-net), or delaying the change to move the type into the 5.0.0 version 

Thanks!

**Comment by sandersaares** [comment]
Great point! Thanks for notifying. I will bump version to 5.0.0.

**Comment by gr-liam** [comment]
It would be great to get a release of https://github.com/prometheus-net/prometheus-net/issues/301 under 4.3.0 if possible
