### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by ReneSorensenBaader** [prometheus-net/prometheus-net#319]
im trying to monitor a client that does not have admin rights, this is causing issues. First i was unable to start the MetricServer server due to net work binding permissions that i fixed with "netsh http add urlacl url=http://*:8882/metrics user=everyone" which mean i can start the server now, but if i access http://localhost:8882/metrics i get a HTTP Error 503. The service is unavailable. If i run the application as an administrator everything works. What am i missing?

**Comment by r3econ** [comment]
I am having the same problem, getting HTTP Error 503 when the app is run inside of a Docker container.

**Comment by sandersaares** [comment]
Configuring permissions on the hosting platform is generally outside the scope of the support that the maintainers of this library can provide. However, if possible you may want to try using `KestrelMetricServer` (requires .NET Core 3.1 or newer) which is known to be more user-friendly and requires less permission grants than the older (but more platform-compatible) `MetricServer`.
