### ISSUE TITLE
PUT and POST methods for the pushgateway behave differently 

### ISSUE THREAD

**Issue by brandonmcclure** [prometheus-net/prometheus-net#322]
Pushgateway supports PUT and POST methods and we should have the ability to choose which method we want to use when using this library with the pushgateway. 

my understanding of the difference comes from [this blog post](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PrometheusPushgatewayDropMetrics):
`If you use PUT, Pushgateway assumes that you are completely authoritative for what metrics currently exist under your grouping key; any metrics that you didn't push are removed and become stale in Prometheus. If you use POST, Pushgateway assumes that you're only authoritative for the metric names that you're using in your push. Metric names that you didn't mention might be handled by some other job, so it doesn't touch metrics from them.`

In my use case each job instance will be authoritative for all of their metrics, and I want to be able to replace them after the job/metricpusher starts. 

There is a open PR #305 that would allow us to configure the method we use to achieve the functionality we need for our specific pushgateway use cases.

**Comment by sandersaares** [comment]
Sounds reasonable. PR merged!
