### ISSUE TITLE
HTTP 503 error when accessing the /metrics endpoint

### ISSUE THREAD

**Issue by r3econ** [prometheus-net/prometheus-net#323]
I have a .NETFramework v4.7.2 app where I am trying to add Prometheus metrics.
I followed the tutorial and added:

```
    var server = new MetricServer(hostname: "*", port: 19090);
    server.Start();
```

However, when I access the endpoint using curl it gives me a `503` error.
I also tried specifying `localhost` instead of `*` and got the same result.

```
curl localhost:19090/metrics

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML>

<HEAD>
	<TITLE>Service Unavailable</TITLE>
	<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii">
</HEAD>

<BODY>
	<h2>Service Unavailable</h2>
	<hr>
	<p>HTTP Error 503. The service is unavailable.</p>
</BODY>

</HTML>
```

No error logs appear in the console. How would I go about debugging it? How can I find out why I'm getting an error?

**Comment by rancourt-martin** [comment]
Same issue here but only from windows. I don't get the 503 when running from a Linux VM

@sandersaares , to reproduce, use the sample from this project

/prometheus-net/Sample.Console.NoAspNetCore

Note: I changed the csproj like this:
<TargetFramework>net7.0</TargetFramework>

and I changed the Program.cs like this:

using var server = new MetricServer(hostname: "*", port: 1234);

**Comment by DanielBck** [comment]
I have been struggling with the same issue and for me it was how i set up the url reservation. It must match what you use as hostname when you create the MetricsServer so in your case it should be:
`netsh http add urlacl url=http://*:1234/metrics user=Everyone`
and you should not have any other url reservations for that url.

In my case i used `netsh http add urlacl url=http://+:1234/metrics user=Everyone` and used the host name when i created the MetricsServer and then i got the 503.
