### ISSUE TITLE
Prometheus Exemplars

### ISSUE THREAD

**Issue by MahammadAgayev** [prometheus-net/prometheus-net#326]
Do you plan to add prometheus exemplars feature?. It is really useful for tracing and prometheus can scrape OpenMetrics format.

**Comment by paladium** [comment]
I agree, that would be really useful feature

**Comment by muradheydarov** [comment]
I am also waiting this feature. Thanks for creating Issue

**Comment by ilkinmammadzada** [comment]
I totally agree and hope using this feature in production ASAP

**Comment by SamilMehdiyev** [comment]
I think it will be very useful feature, thanks a lot.

**Comment by chavalikesavanand** [comment]
+1 would be very useful

**Comment by anwaramoon** [comment]
@sandersaares any plan to support exemplars in this library? or is there way it can be implemented by user using any extensibility point? thanks

**Comment by hsyed-dojo** [comment]
We need this in the near future. Choosing between trailing exemplars in our golang services or the dotnet ones.

 I might be able to find some time to contribute the support.

**Comment by sandersaares** [comment]
Exemplars are now available in 8.0.0 prerelease versions, release version coming soon. All feedback most welcome!
