### ISSUE TITLE
new requisite for Threadpool and completions ports

### ISSUE THREAD

**Issue by dscaravaggi** [prometheus-net/prometheus-net#327]
Hi all,
I noticed that number of availbale threads in Threadpool
and number of availbale completion ports in thread pool is not published
`ThreadPool.GetAvailableThreads(out a, out b);`

this information could be usefull for diagnosing Task Async pattern for network bound applications

thanks to all 
Diego

P.S.: I just searched GetAvailableThreads and completion ports in the source code

**Comment by sandersaares** [comment]
The prometheus-net library is first and foremost intended for whitebox metrics - to expose internal parameters of your application. While it does come with some default metrics to export .NET stats, these are just for sample data purposes and the set of built-in .NET metrics in prometheus-net will not be extended further.

However, there is a related project that might be interested in taking on this feature: https://github.com/djluck/prometheus-net.DotNetRuntime
