### ISSUE TITLE
New library for parsing PromQL

### ISSUE THREAD

**Issue by djluck** [prometheus-net/prometheus-net#334]
Hey @sandersaares, not a bug but a request- I've been working on a library to parse and modify PromQL expressions. If you wouldn't mind spreading some awareness to the wider prometheus-net community by linking to https://github.com/djluck/PromQL.Parser in the README, I'd really appreciate it.

Thanks for all you've done with this project 🙏

**Comment by sandersaares** [comment]
Very cool library! Happy to drop a link!

**Comment by djluck** [comment]
Thanks @sandersaares !
