### ISSUE TITLE
Under some unclear conditions, HttpClientMetrics cause instability

### ISSUE THREAD

**Issue by sandersaares** [prometheus-net/prometheus-net#336]
Observed strange behavior - if "not too many" concurrent requests are made (15?), some requests receive "wrong" data. Unclear what exactly is happening but removing HttpClientMetrics fixed everything so clearly something is fishy here.

Main suspect is the ResponseDuration, as it implemenets some questionable interception logic. Others are far more trivial.

**Comment by imalkevich** [comment]
Indeed, confirmed experimentally that this option causes the issue:
![image](https://user-images.githubusercontent.com/7044304/142375757-da588f34-3fdd-4c5a-8607-638241389ab9.png)

Thanks
