### ISSUE TITLE
Random Response Data after continuous requests

### ISSUE THREAD

**Issue by sielis** [prometheus-net/prometheus-net#337]
With continuous requests on browser (on /metrics) or on powershell (curl requests) I see up to three different responses appearing in random sequence without any recent activity on the server, to excuse any update for the metrics. Can you please help me in identifying the cause of this behavior?

**Comment by sandersaares** [comment]
Please provide instructions to reproduce. A sample of the unexpected responses might also be helpful to analyze the issue.

**Comment by sielis** [comment]
Thank you for the response.  I finally found what was causing that behavior which was not related to the code. It was a setup configuration. I configured the IIS max worker processes to 5 instead of 1. By setting it to 1 solved my issue. 

Thank you.
