### ISSUE TITLE
Support for .NET 6

### ISSUE THREAD

**Issue by dilyana33** [prometheus-net/prometheus-net#341]
Hello, we've migrated our applications to .NET 6 and noticed that the majority of counters are missing now. Do you plan to soon add support for .NET 6?

**Comment by JustinWickMS** [comment]
@dilyana33: Did you resolve this issue on your end?

**Comment by dilyana33** [comment]
@JustinWickMS yes, I saw in the documentation that some of the counters are now deprecated because of performance issues, so we adjusted our metric board
