### ISSUE TITLE
AddCustomLabel not found in released version 5.0.2

### ISSUE THREAD

**Issue by niteshsinghal85** [prometheus-net/prometheus-net#348]
I have installed the last released version(5.0.2)  in my .net core webapi project. and wanted to add some custom label after looking at the example provided in the readme but this is not available in released version.

I see that code is available in the master but no release package is created.

any plan to release new version with these changes

**Comment by darthkurak** [comment]
Same here. Just wanted to use it, and seems to be not available in 5.0.2 release :(

**Comment by spasm** [comment]
Looks like it's in the [5.1 pre-release](https://www.nuget.org/packages/prometheus-net/5.1.0-pre-000215-c81d12d)... hey @sandersaares any rough idea on when 5.1 might be ready for prime time?
