### ISSUE TITLE
Flush metrics when stopping MetricsPusher

### ISSUE THREAD

**Issue by valentynpopov** [prometheus-net/prometheus-net#35]
By default metrics are sent to push gateway every second.  Therefore, a short job taking less than one second won't have a chance to push anything. I believe Stop() should flush local metrics cache.

Pull request: https://github.com/andrasm/prometheus-net/pull/34

**Comment by andrasm** [comment]
Many thanks for the PR. Merged and pushed to nuget.

**Comment by omerlh** [comment]
Is this still working? look like the inner stop does not send metrics anymore, but instead just stop the task. From my experience, it is not doing the same thing - has someone else experience something similar?

**Comment by sandersaares** [comment]
I confirm there has been a regression. Will be fixed in next release.

**Comment by omerlh** [comment]
Thank you for the quick response!

**Comment by sandersaares** [comment]
Preview version `2.1.1-pre-004445-bc00b93` has been published. Please let me know if this fixes the problem for you.

**Comment by omerlh** [comment]
I experienced so many weird issues with prometheus and push gateway, that I gave up. The main issue - metric not exported, even when directly calling the API. So I'm sorry but currently I'm unable to help with testing it :(
