### ISSUE TITLE
MetricHandler.Dispose should be public?

### ISSUE THREAD

**Issue by Cugtyt** [prometheus-net/prometheus-net#355]
I am using KestrelMetricServer following quick start doc, but I found I cannot call Dispose method as MetricHandler.Dispose  is not public.
It should be public as it is a IDisposable then we can call its Dispose(), right?

https://github.com/prometheus-net/prometheus-net/blob/b9c49cd91b17011791fa61b17a86a803518ecb33/Prometheus.NetStandard/MetricHandler.cs#L72

**Comment by sandersaares** [comment]
You are right - the current way it is structured is confusing. It is possible to call Dispose() via using-statement or casting but not directly. `Dispose()` will be public in 8.0.0.
