### ISSUE TITLE
EventCounterAdapter enables all verbose traces

### ISSUE THREAD

**Issue by dennis-yemelyanov** [prometheus-net/prometheus-net#376]
Currently when using `EventCounterAdapter` all verbose events for this source get enabled, as stated here: https://github.com/prometheus-net/prometheus-net/blob/06c59326d0755ebc88c98f23bd608d71d308b7ed/Prometheus/EventCounterAdapter.cs#L180

Some trace sources generate a ton of events when verbose level is enabled, for example `Microsoft.Data.SqlClient.EventSource` generates an event for each row read from a DataReader. This causes a lot of unnecessary string and other event-related object allocations and increases the number of GCs in our application.

Also it seems like to collect metrics we don't really need events and only need event counters. An example here shows that `EventKeywords` should be set to `None`: https://learn.microsoft.com/en-us/sql/connect/ado-net/event-counters?view=sql-server-ver16#in-proc-example

```csharp
if (eventSource.Name.Equals("Microsoft.Data.SqlClient.EventSource"))
{
    var options = new Dictionary<string, string>();
    // define time interval 1 second
    // without defining this parameter event counters will not enabled
    options.Add("EventCounterIntervalSec", "1");
    // enable for the None keyword
    EnableEvents(eventSource, EventLevel.Informational, EventKeywords.None, options);
} 
```

I don't know if it's a standard practice to use `EventKeywords.None` for counters or this is only a pattern that this specific trace source follows though.

Should `EventCountAdapter` also use `EventKeywords.None` instead of `EventKeywords.All` if this a standard practice, or at least make it configurable?

I think the same question applies to `EventLevel`. Setting it to `Verbose` might generate more events than needed for some applications. Would it make sense to make it configurable as well?

**Comment by sandersaares** [comment]
This is fixed in latest version - we now default to Informative and EventKeywords.None (both configurable).
