### ISSUE TITLE
Support for new UpDownCounter Meter planned?

### ISSUE THREAD

**Issue by weltkante** [prometheus-net/prometheus-net#382]
.NET 7 seems to be getting a new meter, `UpDownCounter`. Currently I'm getting an error (using the latest preview package on nuget, `7.1.0-pre-000307-f980713`)

> Instrument ExampleCounter is of an unsupported type: UpDownCounter`1.

The .NET 7 PR where it went in is here: https://github.com/dotnet/runtime/issues/63648

I couldn't find any mentions of this class in a github search against this repos issues so I'm wondering what the plan is about adding support for it. Apparently there is some [commented out code](https://github.com/prometheus-net/prometheus-net/blob/2e9ca5e0fd1c90118b14b43b96cd9e8d34bde041/Prometheus/MeterAdapter.cs#L141) in the repo, so someone must have noticed it at some point.

**Comment by sandersaares** [comment]
Right, this was waiting for .NET 7 final release. Please give a try to prerelease package version 7.1.0-pre-000318-0479f53 and see if it does what you expect.

**Comment by weltkante** [comment]
I'm getting the data I expect to see now, so seems to work
