### ISSUE TITLE
High CPU on idle when published as a single file

### ISSUE THREAD

**Issue by nickbabcock** [prometheus-net/prometheus-net#392]
Since prometheus-net 7.0, there is high CPU usage on idle when the executable is published as a single file:

Reproduce:

```cs
var server = new Prometheus.MetricServer("*", 4445);
server.Start();
Console.ReadLine();
```

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="prometheus-net" Version="7.0.0" />
  </ItemGroup>

</Project>
```

The problem does not appear in prometheus-net 6.0, or if the executable is not published as a single file.

**Comment by sandersaares** [comment]
Interesting find! I am able to reproduce this and have filed a bug for the runtime https://github.com/dotnet/runtime/issues/80064

This problem appears to be related to the [.NET event counter infrastructure](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/event-counters). If you do not care about publishing event counters as metrics, a legitimate workaround would be to disable the event counter integration used by prometheus-net.

You can do this by calling the following on startup, before any metrics APIs are called:

```csharp
Metrics.SuppressDefaultMetrics(new SuppressDefaultMetricOptions
{
    SuppressEventCounters = true
});
```

**Comment by sandersaares** [comment]
This was fixed in .NET 6.0.15 on https://github.com/dotnet/runtime/pull/81238 as well as 7.0.0 on https://github.com/dotnet/runtime/pull/74481.
