### ISSUE TITLE
Is it possible to have different histogram buckets by endpoint

### ISSUE THREAD

**Issue by aemorales2** [prometheus-net/prometheus-net#395]
I have a sample app that has 2 endpoints 

- /weather/forecast
- /weather/humidity

I have the following to ensure I can specify my histogram buckets which do provide the specified bucket 

```asp.net
  app.UseHttpMetrics(opt => {
  opt.ReduceStatusCodeCardinality();
  opt.RequestDuration.Histogram = Metrics.CreateHistogram("http_request_duration_seconds", "http_request_duration_seconds",
      new HistogramConfiguration
      {
          Buckets = Histogram.ExponentialBuckets(0.550, 2, 1),
          LabelNames = new string[4]{HttpRequestLabelNames.Code, HttpRequestLabelNames.Method, 
          HttpRequestLabelNames.Controller, HttpRequestLabelNames.Endpoint},
          SuppressInitialValue = true
      });
  });
```
![image](https://user-images.githubusercontent.com/17433121/211918898-0e2b2ef2-2f1d-4f86-b753-0cb87cfb9b0f.png)

Now to the question in the title:
Is there a way I can specify different buckets for each of the endpoints. Something like having the 0.550 apply to "/weather/forecast" and "0.200" apply to "/weather/humidity"?

**Comment by aemorales2** [comment]
I feel like I might need to leverage making a new custom registry for each endpoint. I'll play around with that to see if I can get along.

**Comment by sandersaares** [comment]
There is no such feature. This is a very specific scenario that would likely require you to write some custom middleware for the duration measurement.
