### ISSUE TITLE
Add new/replace label name in a previously published metric 

### ISSUE THREAD

**Issue by UselessBread** [prometheus-net/prometheus-net#397]
Hello.
Why can't we add new label name or replace old via adding new label name in a previously published metric with labels (something like promQL's behavior - https://stackoverflow.com/questions/54235797/how-to-rename-label-within-a-metric-in-prometheus)? Is it a problem on the side of Prometheus? As far as I researched from docs, and issues section, currently there is no way to add or replace label name. And as it follows from #80 DefaultCollectorRegistry.Clear() is no longer usable. Do you have some workarounds?

**Comment by sandersaares** [comment]
Can you describe in more detail what you are trying to do? It is not obvious what "add new/replace label name" means.

**Comment by sandersaares** [comment]
This should work. What is the code you are using and what is the exact problem you are having?

In pseudocode, what I would do:

1. var counter1 = Metrics.CreateCounter("foo", "", new[] { "first_label" })
2. var counter2 = Metrics.CreateCounter("foo", "", new[] { "first_label", "second_label" })

If you also want to delete counter1, you would need to individually delete each timeseries from it. Something like:

```csharp
foreach (var labelValues in counter1.GetAllLabelValues())
    counter1.RemoveLabelled(labelValues);
```

If this does not work, please post an executable sample project that demonstrates the issue.

**Comment by UselessBread** [comment]
I figured it out. I'm using 5.0.2 version (because of company policies) and it works perfectly fine on the latest version. On 5.0.2 I am getting System.InvalidOperationException: 'Collector matches a previous registration but has a different set of label names.' on your example (the same as in my code)
Thank you for your answers!
