### ISSUE TITLE
MeterAdapter.StartListener() idempotency

### ISSUE THREAD

**Issue by SharanovPavel** [prometheus-net/prometheus-net#398]
Hello!

Since `prometheus-net 7.0.0` `MeterAdapter` is enabled by default ([release](https://github.com/prometheus-net/prometheus-net/releases/tag/v7.0.0)). This change leads to incorrect metrics collection if startup code already has `MeterAdapter.StartListener()` call, e.g. after update from version `6.0.0`. In this case counters will be collected twice (`counter.Add(1)` will be collected as `+2`).

I suppose idempotency should be implemented to fix this issue.

**Comment by sandersaares** [comment]
Good point. There is an extra complication here in that it is conceptually valid to have different adapters wired up for different instruments (perhaps to record them with different settings), so it is not super straightforward. However, what we could do is at least prevent two adapters from being registered with the default options.
