### ISSUE TITLE
How to test SuppressDefaultMetrics?

### ISSUE THREAD

**Issue by repl-james-yoo** [prometheus-net/prometheus-net#401]
Hello. I've seen some examples about how to use `SuppressDefaultMetrics()`, but I also try to know how to test `SuppressDefaultMetrics()` itself. Is there a way for us to test it out?

**Comment by sandersaares** [comment]
The question is unclear to me - what exactly do you wish to achieve?

**Comment by repl-james-yoo** [comment]
@sandersaares In fact, I guess it's fine now. I thought I had to use `SuppressDefaultMetrics()` to do something similar what `Clear()` did in the past (i.e the one that was gone since v3), I've found a better way instead of removing collectors. I will close this issue.
