### ISSUE TITLE
Suggestion: Add documentation on Collectors

### ISSUE THREAD

**Issue by kdawg14** [prometheus-net/prometheus-net#58]
First off, thanks for creating this library.  I've been using it for a couple months now and I think that it's laid out well, and it does precisely what I need it to do.

One thing that confused me, though, starting out was how to hook into things so that I could periodically set the current state of some of my metrics (like current number of messages, RAM usage, etc.).  I started creating a class with a Timer that would periodically update those sorts of metrics... and then later realized that I just needed to use your Collector framework, and that you already created a Collector by default when starting up the server that provided the **exact** items that I was trying to log.  

I'd like to suggest adding some documentation on Collectors, and perhaps moving them from the Advanced folder to a Collectors folder or something similar.  As I was new to Prometheus, I was kind of trying to shy away in general from more advanced stuff, but I didn't think that something like what I wanted (a collector) was really an advanced feature, so I didn't go looking for it there either.  My fault, probably, but still, I think we could make it clearer so that people don't go trying to reinvent what you've already put in.

If you accept pull requests, I'd be happy to create the documentation and get a pull request in to you.

Thanks again!

**Comment by sandersaares** [comment]
Absolutely, a pull request to showcase the more advanced scenarios in the readme would be quite welcome if you are still interested!

**Comment by NikokoFR** [comment]
Hello !
Do you have any update on this topic, i'm VERY interested 👍 

Thanks

**Comment by sandersaares** [comment]
Do you have specific topics you would like to see more documented? Details about your needs can be very helpful.

**Comment by NikokoFR** [comment]
In Prometheus documentation we can read 
"Scheduling

**Metrics should only be pulled from the application when Prometheus scrapes them**, exporters should not perform scrapes based on their own timers. That is, all scrapes should be synchronous.

Accordingly, you should not set timestamps on the metrics you expose, let Prometheus take care of that. If you think you need timestamps, then you probably need the Pushgateway instead.

If a metric is particularly expensive to retrieve, i.e. takes more than a minute, it is acceptable to cache it. This should be noted in the HELP string.

The default scrape timeout for Prometheus is 10 seconds. If your exporter can be expected to exceed this, you should explicitly call this out in your user documentation."

Is there a way to detect when prometheus is querying the API to run the metrics collection in a synchronous mode?

**Comment by sandersaares** [comment]
I have added an example of on-demand collection to the readme file that should satisfy the scenario you describe.

**Comment by NikokoFR** [comment]
Thank you!!

**Comment by sandersaares** [comment]
A fair bit of documentation has been added with v2.0. I will close this issue as there do not appear to be obvious things remaining to document. If anyone has thoughts about what to document, feel free to open a pull request or issue or just comment here.
