### ISSUE TITLE
netstandard13 support

### ISSUE THREAD

**Issue by malachib** [prometheus-net/prometheus-net#79]
Is this impractical now?  If I were to multitarget this into a pull request, would you consider pulling it in?

**Comment by sandersaares** [comment]
No, such a PR would not be pulled. The platform target is currently fixed at .NET Standard 2.0 and likely to remain so for a long time.

You can use an older version of prometheus-net if you want to target older platforms but to keep the library easy to maintain/build/test with a very limited amount of available developer time, it is important to avoid more complicated multi-targeting scenarios.

**Comment by phnx47** [comment]
My fork support multi-targeting: https://github.com/phnx47/Prometheus.Client.

I plan to support this

**Comment by malachib** [comment]
@sandersaares alright.  Not the answer I hoped for, but the answer I needed :)  Please keep up the work! thanks

**Comment by sandersaares** [comment]
I will mark this as closed then.
