### ISSUE TITLE
webapi usage example missing

### ISSUE THREAD

**Issue by mac2000** [prometheus-net/prometheus-net#86]
wondering if I missing something, but it is really not clear from readme how to get started in good old .net webapi, e.g. what should we add and where to Global.asax, or may be Startup.cs or ...

**Comment by dimula** [comment]
I have the same problem. Did you find the solution?

**Comment by sandersaares** [comment]
There is no built-in integration with ASP.NET Web Api in prometheus-net. Your available options are:

Pull requests adding this feature would be welcome (a similar style as the ASP.NET Core integration should be used).

**Comment by sandersaares** [comment]
I will close this as it seems like you have no further questions on this topic. Please feel free to post another issue if it looks like there is something to be done on the subject.
