### ISSUE TITLE
How to apply Basic Auth for /metrics route?

### ISSUE THREAD

**Issue by 0angelic0** [prometheus-net/prometheus-net#92]
Hello,

Right now I can expose /metrics route which will be pulled by Prometheus. Does this library support Basic Auth for the /metrics route?. To prevent unauthorized access to /metrics.

Thank you for this great library :)

**Comment by virth** [comment]
The library it self doesn't provide basic auth by it self. But there are a ton of ways to add basic auth to a dotnet application. It depends on how and where you're using this library.

If it's a ASP.NET Core application you could just inject one of the many available authentication middlewares.

**Comment by sandersaares** [comment]
To expand on the answer above, how ASP.NET Core works is that you can combine different features, often in the form of middleware plugins. Each piece of middleware performs a separate step in the processing of a request.

The most natural way to add authentication is to add an authentication middleware before the prometheus-net middleware is added to the request pipeline.

Here is a nice tutorial on how to build authentication code as attributes or middleware: https://www.johanbostrom.se/blog/adding-basic-auth-to-your-mvc-application-in-dotnet-core

If we take `BasicAuthMiddleware` from that blog, we can add it to our ASP.NET Core pipeline before prometheus-net by replacing the UseMetricServer line with the following:

```
            app.Map("/metrics", metricsApp =>
            {
                metricsApp.UseMiddleware<BasicAuthMiddleware>("Contoso Corporation");

                // We already specified URL prefix above, no need to specify it twice here.
                metricsApp.UseMetricServer("");
            });
```

I will add this example to the readme, as well. Please leave a comment or open a new issue if you still experience difficulties.

**Comment by nowlights** [comment]
How doi i configure prometheus to use this endpoint with basic authentication?
