### ISSUE TITLE
Remove protobuf

### ISSUE THREAD

**Issue by rgl** [prometheus-net/prometheus-net#98]
this library should remove the support for protobuf because [prometheus no longer supports it](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md).

**Comment by sandersaares** [comment]
This is on the roadmap but with a low priority since the existence of protobuf export support does not break anything. However, if anyone reading this has a scenario where the inclusion of protobuf support is a problem, please add a comment and upvote the issue.

**Comment by sandersaares** [comment]
I see that OpenMetrics has reintroduced protobuf as a format. Interesting.

**Comment by sandersaares** [comment]
Version 3.0.0 is now published, with this change included.
